import { AppLanguage, ExerciseCategory, VoicePattern, WorkoutType } from '../../common/enums';
import { LocalizedText } from '../../common/types';
import type { ExerciseSeed } from './exercises.seed-data';

/**
 * Вправи для ротації «Підбір вправ ШІ»: у каталозі була лише одна дихальна вправа й кілька на координацію,
 * а ШІ відводить цим видам ціле заняття на тиждень (силові → координація → розтяжка → дихальні).
 * Тут — спокійні дихальні практики й прості вправи на рівновагу/координацію для дорослих 50+.
 *
 * ⚠️ Загальні рекомендації, не медичні поради; польські тексти перевірити носієм.
 */

const L = AppLanguage;
const T = (uk: string, ru: string, pl: string, en: string): LocalizedText => ({
  [L.UK]: uk,
  [L.RU]: ru,
  [L.PL]: pl,
  [L.EN]: en,
});

const WHO = 'WHO guidelines on physical activity and sedentary behaviour, 2020';
const BREATH_SOURCE = 'Fincham et al., Scientific Reports, 2023';
const CALM_CRITERIA =
  'CALM breathing exercise: the person sits or stands upright and stays in place for most frames; hands may rest on the belly or chest; small movements of the chest/belly or shoulders are expected, large movements are not required. The person must be clearly present.';

const BREATHING_MUSCLES = [
  T('Діафрагма', 'Диафрагма', 'Przepona', 'Diaphragm'),
  T('Нервова система', 'Нервная система', 'Układ nerwowy', 'Nervous system'),
];

export const AI_ROTATION_EXERCISES_SEED: ExerciseSeed[] = [
  // ───────────── дихальні ─────────────
  {
    slug: 'belly-breathing',
    sortOrder: 50,
    category: ExerciseCategory.BREATHING,
    variantGroup: null,
    voicePattern: VoicePattern.BREATH,
    name: T('Дихання животом', 'Дыхание животом', 'Oddychanie brzuchem', 'Belly breathing'),
    targetReps: null,
    targetSeconds: 60,
    recordMaxSec: 60,
    demoVideoUrl: null,
    benefit: T(
      'Вчить дихати глибоко діафрагмою — спокійніше серцебиття й менше напруги в шиї та плечах.',
      'Учит дышать глубоко диафрагмой — спокойнее сердцебиение и меньше напряжения в шее и плечах.',
      'Uczy głębokiego oddychania przeponą — spokojniejsze serce i mniej napięcia w szyi i barkach.',
      'Teaches deep diaphragm breathing for a calmer heartbeat and less tension in the neck and shoulders.',
    ),
    description: T(
      'Сядьте рівно, одну долоню покладіть на живіт, другу — на груди. Повільно вдихніть носом так, щоб піднімалася долоня на животі. Спокійно видихніть ротом. Груди майже не рухаються.',
      'Сядьте ровно, одну ладонь положите на живот, другую — на грудь. Медленно вдохните носом так, чтобы поднималась ладонь на животе. Спокойно выдохните ртом. Грудь почти не двигается.',
      'Usiądź prosto, jedną dłoń połóż na brzuchu, drugą na klatce piersiowej. Powoli wdychaj nosem tak, by unosiła się dłoń na brzuchu. Spokojnie wydychaj ustami. Klatka prawie się nie rusza.',
      'Sit up straight with one hand on your belly and the other on your chest. Breathe in slowly through the nose so the hand on your belly rises. Breathe out calmly through the mouth. The chest barely moves.',
    ),
    safetyInstructions: T(
      'Якщо паморочиться голова — дихайте звичайно й відпочиньте.',
      'Если кружится голова — дышите обычно и отдохните.',
      'Jeśli kręci się w głowie — oddychaj normalnie i odpocznij.',
      'If you feel dizzy, breathe normally and rest.',
    ),
    aiCriteria: CALM_CRITERIA,
    sourceTitle: BREATH_SOURCE,
    sourceUrl: null,
    workoutTypes: [WorkoutType.BREATHING, WorkoutType.MEDITATION],
    durationMin: 2,
    bodyImpact: { muscles: 5, heart: 30, brain: 55, bones: 0, energy: 45 },
    muscles: BREATHING_MUSCLES,
    isActive: true,
  },
  {
    slug: 'box-breathing',
    sortOrder: 51,
    category: ExerciseCategory.BREATHING,
    variantGroup: null,
    voicePattern: VoicePattern.BREATH,
    name: T('Дихання «квадрат»', 'Дыхание «квадрат»', 'Oddech „kwadrat”', 'Box breathing'),
    targetReps: null,
    targetSeconds: 60,
    recordMaxSec: 60,
    demoVideoUrl: null,
    benefit: T(
      'Рівний ритм 4-4-4-4 швидко заспокоює й допомагає зосередитися.',
      'Ровный ритм 4-4-4-4 быстро успокаивает и помогает сосредоточиться.',
      'Równy rytm 4-4-4-4 szybko uspokaja i pomaga się skupić.',
      'An even 4-4-4-4 rhythm calms you quickly and helps you focus.',
    ),
    description: T(
      'Сядьте рівно. Вдих носом на 4 рахунки, затримка на 4, видих на 4, пауза на 4. Повторюйте цей «квадрат» спокійно, без напруги.',
      'Сядьте ровно. Вдох носом на 4 счета, задержка на 4, выдох на 4, пауза на 4. Повторяйте этот «квадрат» спокойно, без напряжения.',
      'Usiądź prosto. Wdech nosem na 4, zatrzymanie na 4, wydech na 4, pauza na 4. Powtarzaj ten „kwadrat” spokojnie, bez napięcia.',
      'Sit up straight. Breathe in through the nose for 4 counts, hold for 4, breathe out for 4, pause for 4. Repeat the "box" calmly, without strain.',
    ),
    safetyInstructions: T(
      'Затримку дихання робіть короткою й комфортною; при дискомфорті — пропустіть затримку.',
      'Задержку дыхания делайте короткой и комфортной; при дискомфорте — пропустите задержку.',
      'Zatrzymanie oddechu niech będzie krótkie i komfortowe; przy dyskomforcie pomiń je.',
      'Keep the breath hold short and comfortable; skip it if it feels uncomfortable.',
    ),
    aiCriteria: CALM_CRITERIA,
    sourceTitle: BREATH_SOURCE,
    sourceUrl: null,
    workoutTypes: [WorkoutType.BREATHING, WorkoutType.MEDITATION],
    durationMin: 2,
    bodyImpact: { muscles: 0, heart: 30, brain: 65, bones: 0, energy: 40 },
    muscles: BREATHING_MUSCLES,
    isActive: true,
  },
  {
    slug: 'long-exhale-breathing',
    sortOrder: 52,
    category: ExerciseCategory.BREATHING,
    variantGroup: null,
    voicePattern: VoicePattern.BREATH,
    name: T(
      'Дихання з довгим видихом',
      'Дыхание с длинным выдохом',
      'Oddech z długim wydechem',
      'Long-exhale breathing',
    ),
    targetReps: null,
    targetSeconds: 60,
    recordMaxSec: 60,
    demoVideoUrl: null,
    benefit: T(
      'Довгий видих знижує напругу й пульс — добре наприкінці заняття та перед сном.',
      'Длинный выдох снижает напряжение и пульс — хорошо в конце занятия и перед сном.',
      'Długi wydech obniża napięcie i tętno — dobry na koniec treningu i przed snem.',
      'A long exhale lowers tension and heart rate — great at the end of a workout and before sleep.',
    ),
    description: T(
      'Сядьте зручно, плечі розслаблені. Вдихніть носом на 4 рахунки, повільно видихніть ротом на 6–8 рахунків, ніби дмете на свічку, не гасячи її.',
      'Сядьте удобно, плечи расслаблены. Вдохните носом на 4 счета, медленно выдохните ртом на 6–8 счетов, будто дуете на свечу, не гася ее.',
      'Usiądź wygodnie, barki rozluźnione. Wdech nosem na 4, powolny wydech ustami na 6–8, jakbyś dmuchał na świecę, nie gasząc jej.',
      'Sit comfortably with relaxed shoulders. Breathe in through the nose for 4 counts and slowly out through the mouth for 6–8 counts, as if blowing on a candle without putting it out.',
    ),
    aiCriteria: CALM_CRITERIA,
    sourceTitle: BREATH_SOURCE,
    sourceUrl: null,
    workoutTypes: [WorkoutType.BREATHING, WorkoutType.MEDITATION],
    durationMin: 2,
    bodyImpact: { muscles: 0, heart: 35, brain: 55, bones: 0, energy: 35 },
    muscles: BREATHING_MUSCLES,
    isActive: true,
  },
  {
    slug: 'arm-raise-breathing',
    sortOrder: 53,
    category: ExerciseCategory.BREATHING,
    variantGroup: null,
    voicePattern: VoicePattern.BREATH,
    name: T(
      'Дихання з підйомом рук',
      'Дыхание с подъемом рук',
      'Oddech z unoszeniem rąk',
      'Breathing with arm raises',
    ),
    targetReps: null,
    targetSeconds: 60,
    recordMaxSec: 60,
    demoVideoUrl: null,
    benefit: T(
      'Розкриває грудну клітку й плечі, допомагає вдихати глибше.',
      'Раскрывает грудную клетку и плечи, помогает вдыхать глубже.',
      'Otwiera klatkę piersiową i barki, pomaga oddychać głębiej.',
      'Opens up the chest and shoulders and helps you breathe more deeply.',
    ),
    description: T(
      'Станьте або сядьте рівно, руки внизу. На вдиху повільно підніміть руки через сторони вгору, на видиху так само повільно опустіть. Рух у темпі дихання.',
      'Встаньте или сядьте ровно, руки внизу. На вдохе медленно поднимите руки через стороны вверх, на выдохе так же медленно опустите. Движение в темпе дыхания.',
      'Stań lub usiądź prosto, ręce w dole. Na wdechu powoli unieś ręce bokami w górę, na wydechu równie powoli opuść. Ruch w tempie oddechu.',
      'Stand or sit up straight with arms down. Breathing in, slowly raise your arms out to the sides and up; breathing out, lower them just as slowly. Move at the pace of your breath.',
    ),
    safetyInstructions: T(
      'Піднімайте руки лише до комфортної висоти, без болю в плечах.',
      'Поднимайте руки только до комфортной высоты, без боли в плечах.',
      'Unoś ręce tylko na wygodną wysokość, bez bólu barków.',
      'Raise your arms only as high as is comfortable, without shoulder pain.',
    ),
    aiCriteria:
      'Slow breathing exercise: the person stands or sits and slowly raises both arms out to the sides and up, then lowers them, in a calm rhythm. Slow and small range is fine.',
    sourceTitle: BREATH_SOURCE,
    sourceUrl: null,
    workoutTypes: [WorkoutType.BREATHING, WorkoutType.MORNING],
    durationMin: 2,
    bodyImpact: { muscles: 15, heart: 30, brain: 45, bones: 10, energy: 50 },
    muscles: [...BREATHING_MUSCLES, T('Плечі', 'Плечи', 'Barki', 'Shoulders')],
    isActive: true,
  },
  {
    slug: 'pursed-lip-breathing',
    sortOrder: 54,
    category: ExerciseCategory.BREATHING,
    variantGroup: null,
    voicePattern: VoicePattern.BREATH,
    name: T(
      'Дихання через зімкнуті губи',
      'Дыхание через сомкнутые губы',
      'Oddech przez zaciśnięte usta',
      'Pursed-lip breathing',
    ),
    targetReps: null,
    targetSeconds: 60,
    recordMaxSec: 60,
    demoVideoUrl: null,
    benefit: T(
      'Полегшує задишку при ходьбі сходами й допомагає легеням працювати рівніше.',
      'Облегчает одышку при ходьбе по лестнице и помогает легким работать ровнее.',
      'Łagodzi zadyszkę na schodach i pomaga płucom pracować równiej.',
      'Eases breathlessness on stairs and helps the lungs work more evenly.',
    ),
    description: T(
      'Сядьте рівно. Вдихніть носом на 2 рахунки. Складіть губи трубочкою й повільно видихайте на 4 рахунки — видих удвічі довший за вдих.',
      'Сядьте ровно. Вдохните носом на 2 счета. Сложите губы трубочкой и медленно выдыхайте на 4 счета — выдох вдвое длиннее вдоха.',
      'Usiądź prosto. Wdech nosem na 2. Złóż usta w dzióbek i powoli wydychaj na 4 — wydech dwa razy dłuższy niż wdech.',
      'Sit up straight. Breathe in through the nose for 2 counts. Purse your lips and breathe out slowly for 4 counts — the exhale is twice as long as the inhale.',
    ),
    aiCriteria: CALM_CRITERIA,
    sourceTitle: BREATH_SOURCE,
    sourceUrl: null,
    workoutTypes: [WorkoutType.BREATHING],
    durationMin: 2,
    bodyImpact: { muscles: 0, heart: 35, brain: 45, bones: 0, energy: 40 },
    muscles: BREATHING_MUSCLES,
    isActive: true,
  },

  // ───────────── координація й рівновага ─────────────
  {
    slug: 'tandem-stand',
    sortOrder: 55,
    category: ExerciseCategory.BALANCE,
    variantGroup: null,
    voicePattern: VoicePattern.HOLD,
    name: T(
      'Стійка «п’ятка до носка»',
      'Стойка «пятка к носку»',
      'Stanie „pięta do palców”',
      'Tandem stand',
    ),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Тренує рівновагу у вузькій стійці — впевненіша хода й менше ризик падіння.',
      'Тренирует равновесие в узкой стойке — увереннее походка и меньше риск падения.',
      'Trenuje równowagę w wąskiej postawie — pewniejszy chód i mniejsze ryzyko upadku.',
      'Trains balance in a narrow stance for a steadier walk and a lower risk of falls.',
    ),
    description: T(
      'Станьте поруч зі стіною. Поставте одну стопу просто перед іншою: п’ятка передньої ноги торкається носка задньої. Тримайте рівновагу, погляд перед собою. На половині часу змініть ноги.',
      'Встаньте рядом со стеной. Поставьте одну стопу прямо перед другой: пятка передней ноги касается носка задней. Держите равновесие, взгляд перед собой. На половине времени смените ноги.',
      'Stań przy ścianie. Postaw jedną stopę tuż przed drugą: pięta przedniej nogi dotyka palców tylnej. Utrzymaj równowagę, wzrok przed siebie. W połowie czasu zmień nogi.',
      'Stand next to a wall. Place one foot directly in front of the other so the front heel touches the back toes. Hold your balance looking ahead. Switch feet halfway through.',
    ),
    safetyInstructions: T(
      'Тримайтеся поруч зі стіною чи спинкою стільця, щоб підстрахуватися.',
      'Держитесь рядом со стеной или спинкой стула, чтобы подстраховаться.',
      'Trzymaj się blisko ściany lub oparcia krzesła, by się asekurować.',
      'Stay close to a wall or chair back so you can steady yourself.',
    ),
    aiCriteria:
      'HOLD exercise: the person stands with one foot directly in front of the other (heel to toe, narrow stance) and keeps balance for most frames; touching a wall lightly is fine.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.COORDINATION],
    durationMin: 1,
    bodyImpact: { muscles: 25, heart: 10, brain: 55, bones: 40, energy: 25 },
    muscles: [
      T('Стабілізатори стопи', 'Стабилизаторы стопы', 'Stabilizatory stopy', 'Foot stabilisers'),
      T('Литки', 'Икры', 'Łydki', 'Calves'),
    ],
    isActive: true,
  },
  {
    slug: 'cross-crawl',
    sortOrder: 56,
    category: ExerciseCategory.BALANCE,
    variantGroup: null,
    voicePattern: VoicePattern.MARCH,
    name: T(
      'Коліно до протилежної долоні',
      'Колено к противоположной ладони',
      'Kolano do przeciwnej dłoni',
      'Cross-body knee touches',
    ),
    targetReps: 16,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Перехресні рухи змушують обидві півкулі працювати разом — краща координація й увага.',
      'Перекрестные движения заставляют оба полушария работать вместе — лучше координация и внимание.',
      'Ruchy naprzemienne angażują obie półkule mózgu — lepsza koordynacja i uwaga.',
      'Cross-body moves make both sides of the brain work together for better coordination and focus.',
    ),
    description: T(
      'Станьте рівно. Підніміть праве коліно й торкніться його лівою долонею, опустіть. Потім ліве коліно — правою долонею. Чергуйте в спокійному темпі, спина рівна.',
      'Встаньте ровно. Поднимите правое колено и коснитесь его левой ладонью, опустите. Затем левое колено — правой ладонью. Чередуйте в спокойном темпе, спина ровная.',
      'Stań prosto. Unieś prawe kolano i dotknij go lewą dłonią, opuść. Potem lewe kolano — prawą dłonią. Zmieniaj w spokojnym tempie, plecy proste.',
      'Stand tall. Lift your right knee and touch it with your left hand, then lower it. Then the left knee with the right hand. Alternate at a calm pace with a straight back.',
    ),
    safetyInstructions: T(
      'Піднімайте коліно лише на комфортну висоту; можна виконувати сидячи на стільці.',
      'Поднимайте колено только на комфортную высоту; можно выполнять сидя на стуле.',
      'Unoś kolano tylko na wygodną wysokość; można ćwiczyć siedząc na krześle.',
      'Lift the knee only as high as is comfortable; you can also do this seated on a chair.',
    ),
    aiCriteria:
      'The person alternately lifts one knee and touches or reaches it with the OPPOSITE hand, standing or seated. Low knee height is fine as long as the cross-body pattern is visible.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.COORDINATION, WorkoutType.WARMUP],
    durationMin: 2,
    bodyImpact: { muscles: 30, heart: 35, brain: 65, bones: 30, energy: 50 },
    muscles: [
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Abs'),
      T('Згиначі стегна', 'Сгибатели бедра', 'Zginacze bioder', 'Hip flexors'),
    ],
    isActive: true,
  },
  {
    slug: 'toe-taps',
    sortOrder: 57,
    category: ExerciseCategory.BALANCE,
    variantGroup: null,
    voicePattern: VoicePattern.MARCH,
    name: T(
      'Торкання носком уперед і вбік',
      'Касания носком вперед и в сторону',
      'Dotknięcia palcami w przód i w bok',
      'Forward and side toe taps',
    ),
    targetReps: 16,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Вчить переносити вагу з ноги на ногу — стійкість під час ходьби й поворотів.',
      'Учит переносить вес с ноги на ногу — устойчивость при ходьбе и поворотах.',
      'Uczy przenoszenia ciężaru z nogi na nogę — stabilność przy chodzeniu i obrotach.',
      'Teaches you to shift weight from leg to leg for stability when walking and turning.',
    ),
    description: T(
      'Станьте рівно, руки на поясі. Торкніться підлоги носком правої ноги попереду, поверніть ногу, потім торкніться збоку й поверніть. Повторіть лівою ногою. Опорна нога трохи зігнута.',
      'Встаньте ровно, руки на поясе. Коснитесь пола носком правой ноги впереди, верните ногу, затем коснитесь сбоку и верните. Повторите левой ногой. Опорная нога слегка согнута.',
      'Stań prosto, ręce na biodrach. Dotknij podłogi palcami prawej nogi z przodu, wróć, potem z boku i wróć. Powtórz lewą nogą. Noga podporowa lekko ugięta.',
      'Stand tall with hands on your hips. Tap the floor in front with your right toes, bring the foot back, then tap to the side and back. Repeat with the left leg. Keep the standing knee soft.',
    ),
    safetyInstructions: T(
      'За потреби тримайтеся за спинку стільця.',
      'При необходимости держитесь за спинку стула.',
      'W razie potrzeby przytrzymaj się oparcia krzesła.',
      'Hold on to a chair back if needed.',
    ),
    aiCriteria:
      'Standing exercise: the person alternately taps one foot forward and to the side and brings it back, switching legs, while balancing on the other leg. Holding a chair is fine.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.COORDINATION, WorkoutType.WARMUP],
    durationMin: 2,
    bodyImpact: { muscles: 30, heart: 30, brain: 55, bones: 35, energy: 40 },
    muscles: [
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Стабілізатори стопи', 'Стабилизаторы стопы', 'Stabilizatory stopy', 'Foot stabilisers'),
    ],
    isActive: true,
  },
  {
    slug: 'side-leg-raise',
    sortOrder: 58,
    category: ExerciseCategory.BALANCE,
    variantGroup: null,
    voicePattern: VoicePattern.RAISE,
    name: T(
      'Відведення ноги вбік стоячи',
      'Отведение ноги в сторону стоя',
      'Odwodzenie nogi w bok na stojąco',
      'Standing side leg raise',
    ),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює бічні м’язи стегна, що тримають таз рівно під час ходьби.',
      'Укрепляет боковые мышцы бедра, которые держат таз ровно при ходьбе.',
      'Wzmacnia boczne mięśnie uda, które trzymają miednicę prosto podczas chodu.',
      'Strengthens the side hip muscles that keep your pelvis level when you walk.',
    ),
    description: T(
      'Станьте боком до стільця й тримайтеся за спинку. Повільно відведіть пряму ногу вбік, не нахиляючи корпус, затримайтеся на секунду й опустіть. Половину повторів — однією ногою, половину — іншою.',
      'Встаньте боком к стулу и держитесь за спинку. Медленно отведите прямую ногу в сторону, не наклоняя корпус, задержитесь на секунду и опустите. Половину повторов — одной ногой, половину — другой.',
      'Stań bokiem do krzesła i trzymaj się oparcia. Powoli odwiedź prostą nogę w bok, nie przechylając tułowia, zatrzymaj na sekundę i opuść. Połowa powtórzeń jedną nogą, połowa drugą.',
      'Stand side-on to a chair and hold the back. Slowly lift your straight leg out to the side without leaning, pause for a second and lower it. Do half the reps with one leg, half with the other.',
    ),
    safetyInstructions: T(
      'Невелика амплітуда — нормально; головне — рівний корпус.',
      'Небольшая амплитуда — нормально; главное — ровный корпус.',
      'Mały zakres ruchu jest w porządku; najważniejszy jest prosty tułów.',
      'A small range is fine; what matters is keeping your body upright.',
    ),
    aiCriteria:
      'Standing exercise: the person lifts one straight leg out to the side and lowers it, repeatedly, usually holding a chair; switching legs halfway is fine. Small range is acceptable.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.COORDINATION, WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 45, heart: 20, brain: 40, bones: 40, energy: 30 },
    muscles: [
      T(
        'Середній сідничний м’яз',
        'Средняя ягодичная мышца',
        'Mięsień pośladkowy średni',
        'Gluteus medius',
      ),
      T('Стабілізатори таза', 'Стабилизаторы таза', 'Stabilizatory miednicy', 'Pelvic stabilisers'),
    ],
    isActive: true,
  },
];
