import { AppLanguage, ExerciseCategory, VoicePattern, WorkoutType } from '../../common/enums';
import { LocalizedText } from '../../common/types';
import type { ExerciseSeed } from './exercises.seed-data';

/**
 * Основний каталог для дорослих, які нормально рухаються (без «вправ на стільці»).
 * Вправи згруповані в різновиди (`variantGroup`): на місці вправи в програмі день у день чергуються
 * вправи однієї групи — присідання → сумо → присідання з підйомом на носки, щоб тренування не набридали
 * й навантаження розподілялось.
 *
 * ⚠️ Тексти «Користь» — загальні фітнес-рекомендації, не медичні поради; польські тексти перевірити носієм.
 */

const L = AppLanguage;
const T = (uk: string, ru: string, pl: string, en: string): LocalizedText => ({
  [L.UK]: uk,
  [L.RU]: ru,
  [L.PL]: pl,
  [L.EN]: en,
});

const WHO = 'WHO guidelines on physical activity and sedentary behaviour, 2020';
const ACSM = "ACSM's Guidelines for Exercise Testing and Prescription, 11th ed.";
const NHS_STRENGTH = 'NHS: Strength exercises for adults';

export const FITNESS_EXERCISES_SEED: ExerciseSeed[] = [
  // ───────────── розминка (warmup) ─────────────
  {
    slug: 'arm-circles',
    sortOrder: 20,
    category: ExerciseCategory.JOINT_MOBILITY,
    variantGroup: 'warmup',
    voicePattern: VoicePattern.CIRCLE,
    name: T('Кола руками', 'Круги руками', 'Krążenia ramion w bok', 'Arm circles'),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Розігріває плечові суглоби й готує руки та спину до навантаження.',
      'Разогревает плечевые суставы и готовит руки и спину к нагрузке.',
      'Rozgrzewa stawy barkowe i przygotowuje ręce oraz plecy do wysiłku.',
      'Warms up the shoulder joints and prepares arms and back for the workout.',
    ),
    description: T(
      'Станьте рівно, ноги на ширині плечей, руки в сторони на рівні плечей. Робіть кола руками: перші 15 секунд — вперед, потім — назад. Кола поступово збільшуйте.',
      'Встаньте ровно, ноги на ширине плеч, руки в стороны на уровне плеч. Делайте круги руками: первые 15 секунд — вперед, затем — назад. Круги постепенно увеличивайте.',
      'Stań prosto, stopy na szerokość barków, ręce w bok na wysokości barków. Wykonuj koła rękami: przez pierwsze 15 sekund do przodu, potem do tyłu. Stopniowo zwiększaj koła.',
      'Stand tall, feet shoulder-width apart, arms out to the sides at shoulder height. Circle your arms: forward for the first 15 seconds, then backward. Gradually make the circles bigger.',
    ),
    aiCriteria:
      'Standing person with both arms extended sideways, drawing circles with the arms (hands move around the shoulder line); arm position visibly changes between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.WARMUP, WorkoutType.MORNING],
    durationMin: 1,
    bodyImpact: { muscles: 30, heart: 25, brain: 15, bones: 20, energy: 55 },
    muscles: [
      T('Дельтоподібні м’язи', 'Дельтовидные мышцы', 'Mięśnie naramienne', 'Deltoids'),
      T('Верх спини', 'Верх спины', 'Górna część pleców', 'Upper back'),
    ],
    isActive: true,
  },
  {
    slug: 'torso-twists',
    sortOrder: 21,
    category: ExerciseCategory.JOINT_MOBILITY,
    variantGroup: 'warmup',
    voicePattern: VoicePattern.TWIST,
    name: T('Повороти корпусу', 'Повороты корпуса', 'Skręty tułowia', 'Torso twists'),
    targetReps: 16,
    targetSeconds: null,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Розминає хребет і м’язи корпусу, знімає скутість після сну чи сидячої роботи.',
      'Разминает позвоночник и мышцы корпуса, снимает скованность после сна или сидячей работы.',
      'Rozluźnia kręgosłup i mięśnie tułowia, zmniejsza sztywność po śnie lub pracy siedzącej.',
      'Loosens the spine and core muscles and relieves stiffness after sleep or desk work.',
    ),
    description: T(
      'Ноги на ширині плечей, коліна м’які, руки зігнуті перед грудьми. Повертайте корпус то вліво, то вправо, таз залишається на місці. Дихайте рівно.',
      'Ноги на ширине плеч, колени мягкие, руки согнуты перед грудью. Поворачивайте корпус то влево, то вправо, таз остается на месте. Дышите ровно.',
      'Stopy na szerokość barków, kolana lekko ugięte, ręce zgięte przed klatką piersiową. Skręcaj tułów raz w lewo, raz w prawo, miednica zostaje w miejscu. Oddychaj równo.',
      'Feet shoulder-width apart, soft knees, elbows bent in front of the chest. Rotate your upper body left and right while the hips stay still. Breathe evenly.',
    ),
    aiCriteria:
      'Standing person rotating the upper body alternately to the left and right while hips stay mostly facing forward; shoulder line visibly turns between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.WARMUP, WorkoutType.MORNING, WorkoutType.STRETCH],
    durationMin: 1,
    bodyImpact: { muscles: 35, heart: 20, brain: 15, bones: 25, energy: 45 },
    muscles: [
      T('Косі м’язи живота', 'Косые мышцы живота', 'Mięśnie skośne brzucha', 'Obliques'),
      T('М’язи спини', 'Мышцы спины', 'Mięśnie pleców', 'Back muscles'),
    ],
    isActive: true,
  },
  {
    slug: 'hip-circles',
    sortOrder: 22,
    category: ExerciseCategory.JOINT_MOBILITY,
    variantGroup: 'warmup',
    voicePattern: VoicePattern.CIRCLE,
    name: T('Кола тазом', 'Круги тазом', 'Krążenia bioder', 'Hip circles'),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Мобілізує кульшові суглоби й поперек — менше дискомфорту під час ходьби та нахилів.',
      'Мобилизует тазобедренные суставы и поясницу — меньше дискомфорта при ходьбе и наклонах.',
      'Uruchamia stawy biodrowe i odcinek lędźwiowy — mniej dyskomfortu przy chodzeniu i skłonach.',
      'Mobilises the hips and lower back for more comfortable walking and bending.',
    ),
    description: T(
      'Ноги трохи ширше плечей, руки на поясі. Описуйте тазом широкі кола: 15 секунд в один бік, потім в інший. Верх тіла майже нерухомий.',
      'Ноги чуть шире плеч, руки на поясе. Описывайте тазом широкие круги: 15 секунд в одну сторону, затем в другую. Верх тела почти неподвижен.',
      'Stopy nieco szerzej niż barki, ręce na biodrach. Zataczaj biodrami szerokie koła: 15 sekund w jedną stronę, potem w drugą. Górna część ciała prawie nieruchoma.',
      'Feet a bit wider than shoulders, hands on hips. Draw wide circles with your hips: 15 seconds one way, then the other. Keep the upper body fairly still.',
    ),
    aiCriteria:
      'Standing person with hands on hips moving the pelvis in circles (hips shift forward, sideways and back while the head stays roughly in place).',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.WARMUP, WorkoutType.MORNING],
    durationMin: 1,
    bodyImpact: { muscles: 25, heart: 20, brain: 10, bones: 30, energy: 40 },
    muscles: [
      T('М’язи тазу', 'Мышцы таза', 'Mięśnie miednicy', 'Hip muscles'),
      T('Поперек', 'Поясница', 'Odcinek lędźwiowy', 'Lower back'),
    ],
    isActive: true,
  },

  // ───────────── кардіо (cardio) ─────────────
  {
    slug: 'jumping-jacks',
    sortOrder: 23,
    category: ExerciseCategory.CARDIO,
    variantGroup: 'cardio',
    voicePattern: VoicePattern.JACKS,
    name: T('Стрибки «зірочка»', 'Прыжки «звездочка»', 'Pajacyki', 'Jumping jacks'),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Швидко піднімає пульс, тренує серце, витривалість і координацію.',
      'Быстро поднимает пульс, тренирует сердце, выносливость и координацию.',
      'Szybko podnosi tętno, trenuje serce, wytrzymałość i koordynację.',
      'Raises your heart rate fast and trains the heart, stamina and coordination.',
    ),
    description: T(
      'Стрибком розставте ноги ширше плечей і одночасно підніміть руки через сторони над головою. Наступним стрибком поверніться у вихідне положення. Приземляйтеся м’яко на передню частину стопи.',
      'Прыжком расставьте ноги шире плеч и одновременно поднимите руки через стороны над головой. Следующим прыжком вернитесь в исходное положение. Приземляйтесь мягко на переднюю часть стопы.',
      'Podskokiem rozstaw nogi szerzej niż barki i jednocześnie unieś ręce bokiem nad głowę. Kolejnym podskokiem wróć do pozycji wyjściowej. Lądowanie miękko na przedniej części stopy.',
      'Jump your feet wider than your shoulders while raising your arms overhead, then jump back to the start. Land softly on the balls of your feet.',
    ),
    safetyInstructions: T(
      'Якщо болять коліна чи є зайва вага — робіть без стрибка, крок у сторону.',
      'Если болят колени — делайте без прыжка, шагом в сторону.',
      'Jeśli bolą kolana — wykonuj bez skoku, krokiem w bok.',
      'If your knees hurt, do it without jumping — step out to the side instead.',
    ),
    aiCriteria:
      'Person alternates between feet together with arms down and feet wide with arms raised overhead (star shape); legs and arms open and close repeatedly across frames.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO, WorkoutType.MORNING],
    durationMin: 1,
    bodyImpact: { muscles: 45, heart: 85, brain: 35, bones: 50, energy: 80 },
    muscles: [
      T('Литки', 'Икры', 'Łydki', 'Calves'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Плечі', 'Плечи', 'Barki', 'Shoulders'),
    ],
    isActive: true,
  },
  {
    slug: 'step-jacks',
    sortOrder: 24,
    category: ExerciseCategory.CARDIO,
    variantGroup: 'cardio',
    voicePattern: VoicePattern.JACKS,
    name: T(
      'Кроки в сторони з руками вгору',
      'Шаги в стороны с руками вверх',
      'Kroki w bok z rękami w górę',
      'Step jacks',
    ),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Кардіо без стрибків: розганяє кров і пульс, м’яко для колін.',
      'Кардио без прыжков: разгоняет кровь и пульс, мягко для коленей.',
      'Cardio bez skoków: pobudza krążenie i tętno, łagodne dla kolan.',
      'Cardio without jumping: gets the blood pumping while staying gentle on the knees.',
    ),
    description: T(
      'Широкий крок правою ногою вбік і одночасно руки через сторони вгору. Приставте ногу й опустіть руки. Повторіть лівою ногою. Темп — енергійний.',
      'Широкий шаг правой ногой в сторону и одновременно руки через стороны вверх. Приставьте ногу и опустите руки. Повторите левой ногой. Темп — энергичный.',
      'Szeroki krok prawą nogą w bok i jednocześnie ręce bokiem w górę. Dostaw nogę i opuść ręce. Powtórz lewą nogą. Tempo energiczne.',
      'Take a wide step to the right while sweeping your arms overhead, bring the foot back and lower the arms. Repeat to the left at a brisk pace.',
    ),
    aiCriteria:
      'Person alternately steps one foot out to the side while raising both arms overhead, then returns; no jump needed. Legs and arms clearly change position.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO, WorkoutType.MORNING, WorkoutType.WARMUP],
    durationMin: 1,
    bodyImpact: { muscles: 35, heart: 70, brain: 30, bones: 35, energy: 70 },
    muscles: [
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T(
        'Внутрішня поверхня стегна',
        'Внутренняя поверхность бедра',
        'Przywodziciele',
        'Inner thighs',
      ),
      T('Плечі', 'Плечи', 'Barki', 'Shoulders'),
    ],
    isActive: true,
  },
  {
    slug: 'high-knees',
    sortOrder: 25,
    category: ExerciseCategory.CARDIO,
    variantGroup: 'cardio',
    voicePattern: VoicePattern.MARCH,
    name: T(
      'Біг на місці з високим підніманням колін',
      'Бег на месте с высоким подниманием колен',
      'Bieg w miejscu z wysokim unoszeniem kolan',
      'High knees',
    ),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Інтенсивне кардіо: зміцнює серце, прес і м’язи-згиначі стегна.',
      'Интенсивное кардио: укрепляет сердце, пресс и мышцы-сгибатели бедра.',
      'Intensywne cardio: wzmacnia serce, brzuch i zginacze bioder.',
      'Intense cardio that strengthens the heart, core and hip flexors.',
    ),
    description: T(
      'Біжіть на місці, піднімаючи коліна приблизно до рівня пояса. Руки працюють як під час бігу, спина рівна. Якщо важко — переходьте на швидкий крок.',
      'Бегите на месте, поднимая колени примерно до уровня пояса. Руки работают как при беге, спина прямая. Если тяжело — переходите на быстрый шаг.',
      'Biegnij w miejscu, unosząc kolana mniej więcej do wysokości pasa. Ręce pracują jak przy biegu, plecy proste. Jeśli jest ciężko — przejdź na szybki marsz.',
      'Run on the spot, bringing your knees up to about waist height. Pump your arms as if running and keep your back straight. If it gets hard, switch to fast marching.',
    ),
    aiCriteria:
      'Person running or fast-marching on the spot, alternately lifting knees high (toward hip level) with arms swinging; legs clearly alternate between frames.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO],
    durationMin: 1,
    bodyImpact: { muscles: 50, heart: 90, brain: 30, bones: 45, energy: 85 },
    muscles: [
      T('Згиначі стегна', 'Сгибатели бедра', 'Zginacze bioder', 'Hip flexors'),
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Abs'),
      T('Литки', 'Икры', 'Łydki', 'Calves'),
    ],
    isActive: true,
  },

  // ───────────── присідання (squat) ─────────────
  {
    slug: 'squat',
    sortOrder: 26,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'squat',
    voicePattern: VoicePattern.SQUAT,
    name: T('Присідання', 'Приседания', 'Przysiady', 'Bodyweight squats'),
    targetReps: 15,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Базова вправа для сильних ніг і сідниць: легше підніматися сходами й носити сумки.',
      'Базовое упражнение для сильных ног и ягодиц: легче подниматься по лестнице и носить сумки.',
      'Podstawowe ćwiczenie na silne nogi i pośladki: łatwiej wchodzić po schodach i nosić zakupy.',
      'The go-to move for strong legs and glutes — stairs and carrying bags get easier.',
    ),
    description: T(
      'Ноги на ширині плечей, носки трохи назовні. Відводьте таз назад і вниз, ніби сідаєте на стілець, до паралелі стегон з підлогою. Коліна дивляться туди ж, куди носки, спина рівна. Відштовхніться п’ятами й встаньте.',
      'Ноги на ширине плеч, носки чуть наружу. Отводите таз назад и вниз, как будто садитесь на стул, до параллели бедер с полом. Колени смотрят туда же, куда носки, спина прямая. Оттолкнитесь пятками и встаньте.',
      'Stopy na szerokość barków, palce lekko na zewnątrz. Cofaj biodra w tył i w dół, jakbyś siadał na krześle, aż uda będą równolegle do podłogi. Kolana w kierunku palców, plecy proste. Odepchnij się piętami i wstań.',
      'Feet shoulder-width apart, toes slightly out. Push your hips back and down as if sitting on a chair until your thighs are about parallel to the floor. Knees track over toes, back straight. Drive through your heels to stand.',
    ),
    safetyInstructions: T(
      'П’яти не відривайте від підлоги. Біль у колінах — зменште глибину.',
      'Пятки не отрывайте от пола. Боль в коленях — уменьшите глубину.',
      'Nie odrywaj pięt od podłogi. Ból kolan — zmniejsz głębokość.',
      'Keep your heels down. If your knees hurt, squat less deep.',
    ),
    aiCriteria:
      'Squat pattern without a seat: hips move back and down with knees bending deeply, then the person stands up straight; body height clearly changes between frames.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 85, heart: 45, brain: 15, bones: 70, energy: 55 },
    muscles: [
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Задня поверхня стегна', 'Задняя поверхность бедра', 'Mięśnie dwugłowe uda', 'Hamstrings'),
    ],
    isActive: true,
  },
  {
    slug: 'sumo-squat',
    sortOrder: 27,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'squat',
    voicePattern: VoicePattern.SQUAT,
    name: T('Присідання сумо', 'Приседания сумо', 'Przysiady sumo', 'Sumo squats'),
    targetReps: 15,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Акцент на внутрішню поверхню стегна й сідниці, розкриває кульшові суглоби.',
      'Акцент на внутреннюю поверхность бедра и ягодицы, раскрывает тазобедренные суставы.',
      'Akcent na wewnętrzną stronę ud i pośladki, otwiera stawy biodrowe.',
      'Targets the inner thighs and glutes and opens up the hips.',
    ),
    description: T(
      'Поставте ноги широко, носки розверніть назовні. Опускайтеся вниз, розводячи коліна в сторони, спина вертикальна. Внизу коротка пауза — і плавно встаньте.',
      'Поставьте ноги широко, носки разверните наружу. Опускайтесь вниз, разводя колени в стороны, спина вертикальна. Внизу короткая пауза — и плавно встаньте.',
      'Rozstaw stopy szeroko, palce skierowane na zewnątrz. Opuszczaj się w dół, rozchylając kolana na boki, plecy pionowo. Krótka pauza na dole i płynnie wstań.',
      'Take a wide stance with toes turned out. Lower down pushing your knees outwards, torso upright. Pause briefly at the bottom, then rise smoothly.',
    ),
    safetyInstructions: T(
      'Коліна не заходять всередину, п’яти на підлозі.',
      'Колени не заваливаются внутрь, пятки на полу.',
      'Kolana nie uciekają do środka, pięty na podłodze.',
      'Don’t let your knees cave in; keep heels down.',
    ),
    aiCriteria:
      'Wide-stance squat with toes turned out: the person lowers the hips straight down with knees pointing outwards and stands back up; height changes between frames.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 40, brain: 15, bones: 65, energy: 50 },
    muscles: [
      T('Привідні м’язи стегна', 'Приводящие мышцы бедра', 'Przywodziciele', 'Adductors'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
    ],
    isActive: true,
  },
  {
    slug: 'squat-calf-raise',
    sortOrder: 28,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'squat',
    voicePattern: VoicePattern.SQUAT,
    name: T(
      'Присідання з підйомом на носки',
      'Приседание с подъемом на носки',
      'Przysiad ze wspięciem na palce',
      'Squat to calf raise',
    ),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Поєднує силу ніг і рівновагу: працюють стегна, сідниці та литки.',
      'Сочетает силу ног и равновесие: работают бедра, ягодицы и икры.',
      'Łączy siłę nóg i równowagę: pracują uda, pośladki i łydki.',
      'Combines leg strength with balance — thighs, glutes and calves all work.',
    ),
    description: T(
      'Зробіть звичайне присідання, а вставаючи, продовжте рух угору й підніміться на носки. На секунду затримайтеся нагорі й опустіться на всю стопу.',
      'Сделайте обычное приседание, а вставая, продолжите движение вверх и поднимитесь на носки. На секунду задержитесь наверху и опуститесь на всю стопу.',
      'Wykonaj zwykły przysiad, a wstając, kontynuuj ruch w górę i wespnij się na palce. Zatrzymaj się na sekundę na górze i opuść na całe stopy.',
      'Do a regular squat, and as you stand, keep rising onto your toes. Hold for a second at the top, then lower your heels.',
    ),
    aiCriteria:
      'Person squats down (knees bend, hips lower), then stands and rises onto the toes with heels lifted; alternating low squat and tall tiptoe positions.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 85, heart: 45, brain: 25, bones: 70, energy: 55 },
    muscles: [
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
      T('Литки', 'Икры', 'Łydki', 'Calves'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
    ],
    isActive: true,
  },

  // ───────────── випади (lunge) ─────────────
  {
    slug: 'reverse-lunge',
    sortOrder: 29,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'lunge',
    voicePattern: VoicePattern.LUNGE,
    name: T('Випади назад', 'Выпады назад', 'Wykroki w tył', 'Reverse lunges'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює кожну ногу окремо й покращує рівновагу. М’якше для колін, ніж випади вперед.',
      'Укрепляет каждую ногу по отдельности и улучшает равновесие. Мягче для коленей, чем выпады вперед.',
      'Wzmacnia każdą nogę osobno i poprawia równowagę. Łagodniejsze dla kolan niż wykroki w przód.',
      'Strengthens each leg separately and improves balance; easier on the knees than forward lunges.',
    ),
    description: T(
      'Зробіть широкий крок однією ногою назад і опустіться, поки обидва коліна не зігнуться приблизно під прямим кутом. Корпус рівний. Поверніться у стійку й повторіть іншою ногою — ноги чергуються.',
      'Сделайте широкий шаг одной ногой назад и опуститесь, пока оба колена не согнутся примерно под прямым углом. Корпус прямой. Вернитесь в стойку и повторите другой ногой — ноги чередуются.',
      'Zrób szeroki krok jedną nogą w tył i opuść się, aż oba kolana zegną się mniej więcej pod kątem prostym. Tułów prosto. Wróć do postawy i powtórz drugą nogą — nogi na zmianę.',
      'Step one foot back and lower until both knees bend to about 90 degrees, torso upright. Return to standing and repeat with the other leg, alternating sides.',
    ),
    safetyInstructions: T(
      'Коліно передньої ноги не виходить за носок. Для рівноваги можна триматися за стіну.',
      'Колено передней ноги не выходит за носок. Для равновесия можно держаться за стену.',
      'Kolano przedniej nogi nie wychodzi przed palce. Dla równowagi możesz trzymać się ściany.',
      'Keep the front knee behind your toes. Hold a wall for balance if needed.',
    ),
    aiCriteria:
      'Person alternately steps one leg backward and lowers into a lunge (both knees bent, back knee toward the floor), then returns to standing; legs alternate between repetitions.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 45, brain: 25, bones: 65, energy: 55 },
    muscles: [
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T(
        'М’язи-стабілізатори',
        'Мышцы-стабилизаторы',
        'Mięśnie stabilizujące',
        'Stabiliser muscles',
      ),
    ],
    isActive: true,
  },
  {
    slug: 'side-lunge',
    sortOrder: 30,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'lunge',
    voicePattern: VoicePattern.LUNGE,
    name: T('Бокові випади', 'Боковые выпады', 'Wykroki w bok', 'Side lunges'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Тренує ноги в боковій площині й розтягує внутрішню поверхню стегна.',
      'Тренирует ноги в боковой плоскости и растягивает внутреннюю поверхность бедра.',
      'Trenuje nogi w płaszczyźnie bocznej i rozciąga wewnętrzną stronę ud.',
      'Works the legs side-to-side and stretches the inner thighs.',
    ),
    description: T(
      'З широкої стійки перенесіть вагу на одну ногу й присядьте на неї, відводячи таз назад; друга нога пряма. Поверніться в центр і повторіть в інший бік.',
      'Из широкой стойки перенесите вес на одну ногу и присядьте на нее, отводя таз назад; другая нога прямая. Вернитесь в центр и повторите в другую сторону.',
      'Z szerokiej postawy przenieś ciężar na jedną nogę i przysiądź na niej, cofając biodra; druga noga prosta. Wróć na środek i powtórz w drugą stronę.',
      'From a wide stance, shift your weight onto one leg and sit back into it while the other leg stays straight. Return to centre and repeat on the other side.',
    ),
    aiCriteria:
      'Wide stance; the person alternately bends one knee and shifts the hips sideways and back over that leg while the other leg stays straight, then returns to centre.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.STRETCH],
    durationMin: 2,
    bodyImpact: { muscles: 75, heart: 40, brain: 20, bones: 60, energy: 50 },
    muscles: [
      T('Привідні м’язи стегна', 'Приводящие мышцы бедра', 'Przywodziciele', 'Adductors'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
    ],
    isActive: true,
  },
  {
    slug: 'forward-lunge',
    sortOrder: 31,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'lunge',
    voicePattern: VoicePattern.LUNGE,
    name: T('Випади вперед', 'Выпады вперед', 'Wykroki w przód', 'Forward lunges'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Розвиває силу ніг, стійкість і координацію — як при ходьбі широким кроком.',
      'Развивает силу ног, устойчивость и координацию — как при ходьбе широким шагом.',
      'Rozwija siłę nóg, stabilność i koordynację — jak przy chodzeniu długim krokiem.',
      'Builds leg strength, stability and coordination, like walking with long strides.',
    ),
    description: T(
      'Зробіть широкий крок уперед і опустіться, згинаючи обидва коліна. Відштовхніться передньою ногою й поверніться у стійку. Чергуйте ноги.',
      'Сделайте широкий шаг вперед и опуститесь, сгибая оба колена. Оттолкнитесь передней ногой и вернитесь в стойку. Чередуйте ноги.',
      'Zrób szeroki krok w przód i opuść się, zginając oba kolana. Odepchnij się przednią nogą i wróć do postawy. Nogi na zmianę.',
      'Take a long step forward and lower by bending both knees. Push off the front foot back to standing. Alternate legs.',
    ),
    safetyInstructions: T(
      'Крок достатньо широкий, щоб коліно не виходило за носок.',
      'Шаг достаточно широкий, чтобы колено не выходило за носок.',
      'Krok na tyle szeroki, by kolano nie wychodziło przed palce.',
      'Step far enough that the front knee stays behind the toes.',
    ),
    aiCriteria:
      'Person alternately steps one leg forward into a lunge (front knee bent, back knee lowering), then pushes back to standing; legs alternate.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 45, brain: 25, bones: 65, energy: 55 },
    muscles: [
      T('Квадрицепси', 'Квадрицепсы', 'Mięśnie czworogłowe', 'Quadriceps'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Литки', 'Икры', 'Łydki', 'Calves'),
    ],
    isActive: true,
  },

  // ───────────── віджимання (push) ─────────────
  {
    slug: 'incline-push-up',
    sortOrder: 32,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'push',
    voicePattern: VoicePattern.PUSH,
    name: T(
      'Віджимання від опори',
      'Отжимания от опоры',
      'Pompki na podwyższeniu',
      'Incline push-ups',
    ),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює груди, руки й плечі — легше відчиняти двері, піднімати й штовхати.',
      'Укрепляет грудь, руки и плечи — легче открывать двери, поднимать и толкать.',
      'Wzmacnia klatkę piersiową, ręce i barki — łatwiej otwierać drzwi, podnosić i pchać.',
      'Strengthens chest, arms and shoulders for easier pushing, lifting and opening doors.',
    ),
    description: T(
      'Упріться руками в край стола, дивана чи підвіконня трохи ширше плечей, тіло — рівна лінія від голови до п’ят. Зігніть руки, опускаючи груди до опори, і випряміть їх.',
      'Упритесь руками в край стола, дивана или подоконника чуть шире плеч, тело — прямая линия от головы до пяток. Согните руки, опуская грудь к опоре, и выпрямите их.',
      'Oprzyj dłonie o krawędź stołu, kanapy lub parapetu nieco szerzej niż barki, ciało w linii prostej od głowy do pięt. Zegnij ręce, opuszczając klatkę do podparcia, i wyprostuj je.',
      'Place your hands on the edge of a table, sofa or windowsill slightly wider than your shoulders, body straight from head to heels. Bend your elbows to lower your chest, then press back up.',
    ),
    safetyInstructions: T(
      'Опора має бути стійкою й не ковзати.',
      'Опора должна быть устойчивой и не скользить.',
      'Podparcie musi być stabilne i nie może się przesuwać.',
      'Make sure the surface is stable and won’t slide.',
    ),
    aiCriteria:
      'Person leaning on a raised surface (table, sofa, counter) with straight body, repeatedly bending and straightening the arms so the chest moves toward the surface and away.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 75, heart: 35, brain: 10, bones: 55, energy: 45 },
    muscles: [
      T('Грудні м’язи', 'Грудные мышцы', 'Mięśnie klatki piersiowej', 'Chest'),
      T('Трицепси', 'Трицепсы', 'Tricepsy', 'Triceps'),
      T('Плечі', 'Плечи', 'Barki', 'Shoulders'),
    ],
    isActive: true,
  },
  {
    slug: 'knee-push-up',
    sortOrder: 33,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'push',
    voicePattern: VoicePattern.PUSH,
    name: T('Віджимання з колін', 'Отжимания с колен', 'Pompki na kolanach', 'Knee push-ups'),
    targetReps: 10,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Наступний крок після віджимань від опори: сильніші груди, руки й прес.',
      'Следующий шаг после отжиманий от опоры: сильнее грудь, руки и пресс.',
      'Kolejny krok po pompkach na podwyższeniu: silniejsza klatka, ręce i brzuch.',
      'The next step after incline push-ups: stronger chest, arms and core.',
    ),
    description: T(
      'Станьте на коліна, долоні на підлозі трохи ширше плечей. Тіло від голови до колін — рівна лінія. Опустіть груди до підлоги, згинаючи лікті, і вижміться вгору.',
      'Встаньте на колени, ладони на полу чуть шире плеч. Тело от головы до коленей — прямая линия. Опустите грудь к полу, сгибая локти, и выжмитесь вверх.',
      'Uklęknij, dłonie na podłodze nieco szerzej niż barki. Ciało od głowy do kolan w linii prostej. Opuść klatkę do podłogi, zginając łokcie, i wypchnij się w górę.',
      'Kneel with hands on the floor slightly wider than shoulders, body straight from head to knees. Lower your chest toward the floor by bending the elbows, then push back up.',
    ),
    safetyInstructions: T(
      'Під коліна покладіть рушник. Поперек не прогинайте.',
      'Под колени положите полотенце. Поясницу не прогибайте.',
      'Pod kolana połóż ręcznik. Nie wyginaj odcinka lędźwiowego.',
      'Put a towel under your knees and don’t let your lower back sag.',
    ),
    aiCriteria:
      'Person on knees and hands on the floor, body straight from head to knees, repeatedly lowering the chest toward the floor and pushing back up (elbows bend and straighten).',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 35, brain: 10, bones: 55, energy: 45 },
    muscles: [
      T('Грудні м’язи', 'Грудные мышцы', 'Mięśnie klatki piersiowej', 'Chest'),
      T('Трицепси', 'Трицепсы', 'Tricepsy', 'Triceps'),
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Core'),
    ],
    isActive: true,
  },
  {
    slug: 'push-up',
    sortOrder: 34,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'push',
    voicePattern: VoicePattern.PUSH,
    name: T('Віджимання', 'Отжимания', 'Pompki', 'Push-ups'),
    targetReps: 8,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Класика сили верхньої частини тіла: груди, руки, плечі й прес одночасно.',
      'Классика силы верхней части тела: грудь, руки, плечи и пресс одновременно.',
      'Klasyka siły górnej części ciała: klatka, ręce, barki i brzuch naraz.',
      'The classic upper-body strength move: chest, arms, shoulders and core at once.',
    ),
    description: T(
      'Упор лежачи: долоні трохи ширше плечей, ноги разом на носках, тіло — рівна лінія. Опускайтеся, поки груди майже не торкнуться підлоги, і вижміться вгору. Важко — ставайте на коліна.',
      'Упор лежа: ладони чуть шире плеч, ноги вместе на носках, тело — прямая линия. Опускайтесь, пока грудь почти не коснется пола, и выжмитесь вверх. Тяжело — встаньте на колени.',
      'Podpór przodem: dłonie nieco szerzej niż barki, nogi razem na palcach, ciało w linii prostej. Opuszczaj się, aż klatka prawie dotknie podłogi, i wypchnij się w górę. Za ciężko — oprzyj kolana.',
      'High plank: hands slightly wider than shoulders, feet together on toes, body in a straight line. Lower until your chest nearly touches the floor, then push up. Too hard? Drop to your knees.',
    ),
    safetyInstructions: T(
      'Таз не провисає й не задирається. Біль у зап’ястях — упирайтеся на кулаки.',
      'Таз не провисает и не задирается. Боль в запястьях — упирайтесь на кулаки.',
      'Biodra nie opadają ani nie unoszą się. Ból nadgarstków — oprzyj się na pięściach.',
      'Hips neither sag nor pike up. Wrist pain? Press up on your fists.',
    ),
    aiCriteria:
      'Person in a plank on hands and toes (or knees), body straight, repeatedly lowering the chest toward the floor and pushing back up; elbow angle changes between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 90, heart: 45, brain: 10, bones: 60, energy: 50 },
    muscles: [
      T('Грудні м’язи', 'Грудные мышцы', 'Mięśnie klatki piersiowej', 'Chest'),
      T('Трицепси', 'Трицепсы', 'Tricepsy', 'Triceps'),
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Core'),
    ],
    isActive: true,
  },

  // ───────────── кор (core) ─────────────
  {
    slug: 'plank',
    sortOrder: 35,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'core',
    voicePattern: VoicePattern.HOLD,
    name: T('Планка', 'Планка', 'Deska', 'Plank'),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює прес і спину — основа гарної постави й здорового попереку.',
      'Укрепляет пресс и спину — основа хорошей осанки и здоровой поясницы.',
      'Wzmacnia brzuch i plecy — podstawa dobrej postawy i zdrowego odcinka lędźwiowego.',
      'Strengthens abs and back — the foundation of good posture and a healthy lower back.',
    ),
    description: T(
      'Упріться в підлогу передпліччями (лікті під плечима) і носками. Тіло — рівна лінія від голови до п’ят, живіт підтягнутий. Тримайте положення й дихайте рівно.',
      'Упритесь в пол предплечьями (локти под плечами) и носками. Тело — прямая линия от головы до пяток, живот подтянут. Держите положение и дышите ровно.',
      'Oprzyj się na przedramionach (łokcie pod barkami) i palcach stóp. Ciało w linii prostej od głowy do pięt, brzuch napięty. Utrzymuj pozycję i oddychaj równo.',
      'Rest on your forearms (elbows under shoulders) and toes. Keep a straight line from head to heels with your belly tight. Hold and breathe steadily.',
    ),
    safetyInstructions: T(
      'Не затримуйте дихання. Важко — опустіть коліна на підлогу.',
      'Не задерживайте дыхание. Тяжело — опустите колени на пол.',
      'Nie wstrzymuj oddechu. Za ciężko — opuść kolana na podłogę.',
      'Don’t hold your breath. Too hard? Lower your knees to the floor.',
    ),
    aiCriteria:
      'HOLD exercise: the person stays in a forearm or high plank on the floor with the body roughly straight from head to heels (or knees) for most of the time. Little movement is expected; lying flat, sitting or standing is not a plank.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 1,
    bodyImpact: { muscles: 75, heart: 30, brain: 15, bones: 40, energy: 40 },
    muscles: [
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Abs'),
      T('М’язи спини', 'Мышцы спины', 'Mięśnie pleców', 'Back muscles'),
      T('Плечі', 'Плечи', 'Barki', 'Shoulders'),
    ],
    isActive: true,
  },
  {
    slug: 'bird-dog',
    sortOrder: 36,
    category: ExerciseCategory.BALANCE,
    variantGroup: 'core',
    voicePattern: VoicePattern.REACH,
    name: T('«Птах-собака»', '«Птица-собака»', '„Pies-ptak”', 'Bird dog'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Стабілізує поперек і тренує координацію — одна з найкорисніших вправ для спини.',
      'Стабилизирует поясницу и тренирует координацию — одно из самых полезных упражнений для спины.',
      'Stabilizuje odcinek lędźwiowy i trenuje koordynację — jedno z najzdrowszych ćwiczeń na plecy.',
      'Stabilises the lower back and trains coordination — one of the best moves for a healthy back.',
    ),
    description: T(
      'Станьте на карачки: долоні під плечима, коліна під стегнами. Одночасно витягніть праву руку вперед і ліву ногу назад до однієї лінії з тілом. Затримайтеся на секунду, поверніться й повторіть іншою парою.',
      'Встаньте на четвереньки: ладони под плечами, колени под бедрами. Одновременно вытяните правую руку вперед и левую ногу назад до одной линии с телом. Задержитесь на секунду, вернитесь и повторите другой парой.',
      'Uklęknij na czworakach: dłonie pod barkami, kolana pod biodrami. Jednocześnie wyciągnij prawą rękę w przód i lewą nogę w tył, w jednej linii z ciałem. Zatrzymaj się na sekundę, wróć i powtórz drugą parą.',
      'Get on all fours, hands under shoulders and knees under hips. Extend your right arm forward and left leg back in line with your body. Hold a second, return and switch sides.',
    ),
    aiCriteria:
      'Person on hands and knees alternately extending one arm forward and the opposite leg backward to body level, then returning; the extended limbs change between repetitions.',
    sourceTitle: 'McGill S., Low Back Disorders, 3rd ed.',
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 55, heart: 20, brain: 40, bones: 35, energy: 35 },
    muscles: [
      T('Розгиначі спини', 'Разгибатели спины', 'Prostowniki grzbietu', 'Back extensors'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Core'),
    ],
    isActive: true,
  },
  {
    slug: 'dead-bug',
    sortOrder: 37,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'core',
    voicePattern: VoicePattern.REACH,
    // У спорті — «мертвий жук» (dead bug); назва описує сам рух, щоб було зрозуміло, що робити
    name: T(
      'Прес лежачи: рука й протилежна нога',
      'Пресс лежа: рука и противоположная нога',
      'Brzuch leżąc: ręka i przeciwna noga',
      'Dead bug: opposite arm and leg',
    ),
    targetReps: 10,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює глибокі м’язи живота без навантаження на спину.',
      'Укрепляет глубокие мышцы живота без нагрузки на спину.',
      'Wzmacnia głębokie mięśnie brzucha bez obciążania pleców.',
      'Builds deep core strength without stressing the back.',
    ),
    description: T(
      'Ляжте на спину, руки витягніть угору до стелі, ноги підніміть і зігніть у колінах під прямим кутом. Поперек притиснутий до підлоги. Одночасно повільно опустіть праву руку за голову й випряміть ліву ногу вперед, не торкаючись підлоги. Поверніться у вихідне положення й повторіть лівою рукою та правою ногою. Один повтор — одна сторона.',
      'Лягте на спину, руки вытяните вверх к потолку, ноги поднимите и согните в коленях под прямым углом. Поясница прижата к полу. Одновременно медленно опустите правую руку за голову и выпрямите левую ногу вперед, не касаясь пола. Вернитесь в исходное положение и повторите левой рукой и правой ногой. Один повтор — одна сторона.',
      'Połóż się na plecach, wyciągnij ręce w górę do sufitu, unieś nogi zgięte w kolanach pod kątem prostym. Odcinek lędźwiowy dociśnięty do podłogi. Jednocześnie powoli opuść prawą rękę za głowę i wyprostuj lewą nogę w przód, nie dotykając podłogi. Wróć do pozycji wyjściowej i powtórz lewą ręką i prawą nogą. Jedno powtórzenie — jedna strona.',
      'Lie on your back with arms reaching up to the ceiling and legs lifted, knees bent at 90 degrees. Press your lower back into the floor. At the same time, slowly lower your right arm overhead and straighten your left leg forward without touching the floor. Return to the start and repeat with the left arm and right leg. One rep = one side.',
    ),
    aiCriteria:
      'Person lying on their back (seen from the side or at an angle) with arms pointing up and knees bent in the air, alternately lowering one arm overhead and the opposite leg toward the floor, then returning. Small range and slow tempo are fine; it is enough that arms and legs clearly move down and back in an alternating way. Lowering both legs or same-side arm and leg sometimes is a minor form issue, not a reason to reject.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 60, heart: 20, brain: 35, bones: 25, energy: 35 },
    muscles: [
      T(
        'Поперечний м’яз живота',
        'Поперечная мышца живота',
        'Mięsień poprzeczny brzucha',
        'Transverse abs',
      ),
      T('Прес', 'Пресс', 'Mięśnie brzucha', 'Abs'),
    ],
    isActive: true,
  },

  // ───────────── задня поверхня тіла (posterior) ─────────────
  {
    slug: 'glute-bridge',
    sortOrder: 38,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'posterior',
    voicePattern: VoicePattern.BRIDGE,
    name: T('Сідничний місток', 'Ягодичный мостик', 'Mostek biodrowy', 'Glute bridge'),
    targetReps: 15,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Вмикає сідниці й розвантажує поперек — корисно всім, хто багато сидить.',
      'Включает ягодицы и разгружает поясницу — полезно всем, кто много сидит.',
      'Aktywuje pośladki i odciąża odcinek lędźwiowy — dobre dla każdego, kto dużo siedzi.',
      'Wakes up the glutes and takes load off the lower back — great if you sit a lot.',
    ),
    description: T(
      'Ляжте на спину, ноги зігнуті, стопи на підлозі на ширині стегон, руки вздовж тіла. Стисніть сідниці й підніміть таз, щоб тіло від плечей до колін стало рівною лінією. Затримайтеся на секунду й опустіться.',
      'Лягте на спину, ноги согнуты, стопы на полу на ширине бедер, руки вдоль тела. Сожмите ягодицы и поднимите таз, чтобы тело от плеч до коленей стало прямой линией. Задержитесь на секунду и опуститесь.',
      'Połóż się na plecach, nogi zgięte, stopy na podłodze na szerokość bioder, ręce wzdłuż ciała. Napnij pośladki i unieś biodra, aż ciało od barków do kolan utworzy linię prostą. Zatrzymaj się na sekundę i opuść.',
      'Lie on your back, knees bent, feet hip-width on the floor, arms by your sides. Squeeze your glutes and lift your hips until your body forms a line from shoulders to knees. Hold a second and lower.',
    ),
    aiCriteria:
      'Person lying on their back with knees bent and feet on the floor, repeatedly lifting the hips up (body straight from shoulders to knees) and lowering them back down.',
    sourceTitle: NHS_STRENGTH,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 70, heart: 25, brain: 10, bones: 45, energy: 40 },
    muscles: [
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Задня поверхня стегна', 'Задняя поверхность бедра', 'Mięśnie dwugłowe uda', 'Hamstrings'),
      T('Поперек', 'Поясница', 'Odcinek lędźwiowy', 'Lower back'),
    ],
    isActive: true,
  },
  {
    slug: 'superman',
    sortOrder: 39,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'posterior',
    voicePattern: VoicePattern.RAISE,
    name: T('«Супермен»', '«Супермен»', '„Superman”', 'Superman'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює м’язи спини, які тримають поставу, — менше сутулості.',
      'Укрепляет мышцы спины, которые держат осанку, — меньше сутулости.',
      'Wzmacnia mięśnie pleców utrzymujące postawę — mniej garbienia się.',
      'Strengthens the back muscles that hold your posture — less slouching.',
    ),
    description: T(
      'Ляжте на живіт, руки витягнуті вперед. Одночасно підніміть руки, груди й ноги на кілька сантиметрів від підлоги, погляд униз. Затримайтеся на 2 секунди й опустіться.',
      'Лягте на живот, руки вытянуты вперед. Одновременно поднимите руки, грудь и ноги на несколько сантиметров от пола, взгляд вниз. Задержитесь на 2 секунды и опуститесь.',
      'Połóż się na brzuchu, ręce wyciągnięte w przód. Jednocześnie unieś ręce, klatkę i nogi kilka centymetrów nad podłogę, wzrok w dół. Zatrzymaj się na 2 sekundy i opuść.',
      'Lie face down with arms stretched forward. Lift your arms, chest and legs a few centimetres off the floor, eyes down. Hold for 2 seconds and lower.',
    ),
    safetyInstructions: T(
      'Не закидайте голову, шия — продовження хребта.',
      'Не запрокидывайте голову, шея — продолжение позвоночника.',
      'Nie odchylaj głowy, szyja jest przedłużeniem kręgosłupa.',
      'Don’t crank your head back; keep your neck in line with the spine.',
    ),
    aiCriteria:
      'Person lying face down repeatedly lifting arms, chest and legs off the floor at the same time and lowering them; the body arches slightly up and flattens between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 60, heart: 20, brain: 10, bones: 40, energy: 35 },
    muscles: [
      T('Розгиначі спини', 'Разгибатели спины', 'Prostowniki grzbietu', 'Back extensors'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
      T('Задні дельти', 'Задние дельты', 'Tylne aktony mięśni naramiennych', 'Rear delts'),
    ],
    isActive: true,
  },
  {
    slug: 'good-morning',
    sortOrder: 40,
    category: ExerciseCategory.STRENGTH,
    variantGroup: 'posterior',
    voicePattern: VoicePattern.FOLD,
    name: T(
      'Нахили «гуд монінг»',
      'Наклоны «гуд морнинг»',
      'Skłony „good morning”',
      'Good mornings',
    ),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Навчає правильно нахилятися й піднімати речі, зміцнює спину та задню поверхню стегна.',
      'Учит правильно наклоняться и поднимать вещи, укрепляет спину и заднюю поверхность бедра.',
      'Uczy prawidłowego schylania się i podnoszenia rzeczy, wzmacnia plecy i tył ud.',
      'Teaches safe bending and lifting while strengthening the back and hamstrings.',
    ),
    description: T(
      'Ноги на ширині стегон, коліна злегка зігнуті, руки за головою. Із рівною спиною нахиляйтеся вперед, відводячи таз назад, до майже горизонтального корпусу. Поверніться вгору, стискаючи сідниці.',
      'Ноги на ширине бедер, колени слегка согнуты, руки за головой. С прямой спиной наклоняйтесь вперед, отводя таз назад, почти до горизонтали корпуса. Вернитесь вверх, сжимая ягодицы.',
      'Stopy na szerokość bioder, kolana lekko ugięte, ręce za głową. Z prostymi plecami pochylaj się w przód, cofając biodra, prawie do poziomu tułowia. Wróć w górę, napinając pośladki.',
      'Feet hip-width, knees soft, hands behind your head. Keeping your back flat, hinge forward by pushing your hips back until your torso is nearly horizontal. Squeeze your glutes to come back up.',
    ),
    safetyInstructions: T(
      'Спина рівна, без округлення. Біль у спині — зменште амплітуду.',
      'Спина прямая, без скругления. Боль в спине — уменьшите амплитуду.',
      'Plecy proste, bez zaokrąglania. Ból pleców — zmniejsz zakres ruchu.',
      'Keep your back flat, never rounded. Back pain? Reduce the range.',
    ),
    aiCriteria:
      'Standing person with hands behind the head repeatedly hinging forward at the hips with a flat back (torso tilts toward horizontal, hips move back), then standing tall.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.STRETCH],
    durationMin: 2,
    bodyImpact: { muscles: 65, heart: 25, brain: 10, bones: 45, energy: 40 },
    muscles: [
      T('Задня поверхня стегна', 'Задняя поверхность бедра', 'Mięśnie dwugłowe uda', 'Hamstrings'),
      T('Розгиначі спини', 'Разгибатели спины', 'Prostowniki grzbietu', 'Back extensors'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
    ],
    isActive: true,
  },

  // ───────────── баланс (balance) ─────────────
  {
    slug: 'single-leg-stand',
    sortOrder: 41,
    category: ExerciseCategory.BALANCE,
    variantGroup: 'balance',
    voicePattern: VoicePattern.HOLD,
    name: T(
      'Стійка на одній нозі',
      'Стойка на одной ноге',
      'Stanie na jednej nodze',
      'Single-leg stand',
    ),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Тренує рівновагу й стабілізатори гомілковостопу — менше ризик підвернути ногу.',
      'Тренирует равновесие и стабилизаторы голеностопа — меньше риск подвернуть ногу.',
      'Trenuje równowagę i stabilizatory stawu skokowego — mniejsze ryzyko skręcenia kostki.',
      'Trains balance and ankle stabilisers, lowering the risk of rolling an ankle.',
    ),
    description: T(
      'Станьте рівно, підніміть одну ногу, зігнувши її в коліні. Тримайте рівновагу 15 секунд, погляд у одну точку, потім змініть ногу. Для ускладнення — заплющте очі.',
      'Встаньте ровно, поднимите одну ногу, согнув ее в колене. Держите равновесие 15 секунд, взгляд в одну точку, затем смените ногу. Для усложнения — закройте глаза.',
      'Stań prosto, unieś jedną nogę, zginając ją w kolanie. Utrzymaj równowagę 15 sekund, wzrok w jeden punkt, potem zmień nogę. Trudniej — zamknij oczy.',
      'Stand tall and lift one foot, bending the knee. Hold your balance for 15 seconds looking at a fixed point, then switch legs. For a challenge, close your eyes.',
    ),
    safetyInstructions: T(
      'Станьте поруч зі стіною чи спинкою стільця, щоб за потреби підстрахуватися.',
      'Встаньте рядом со стеной или спинкой стула, чтобы при необходимости подстраховаться.',
      'Stań obok ściany lub oparcia krzesła, by w razie potrzeby się przytrzymać.',
      'Stand next to a wall or chair back so you can steady yourself if needed.',
    ),
    aiCriteria:
      'HOLD exercise: the person stands on one leg with the other foot lifted off the floor for most frames (switching legs about halfway is fine). Standing on both feet the whole time is not correct.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.COORDINATION, WorkoutType.MORNING],
    durationMin: 1,
    bodyImpact: { muscles: 35, heart: 15, brain: 50, bones: 45, energy: 30 },
    muscles: [
      T('Литки', 'Икры', 'Łydki', 'Calves'),
      T('Стабілізатори стопи', 'Стабилизаторы стопы', 'Stabilizatory stopy', 'Foot stabilisers'),
      T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes'),
    ],
    isActive: true,
  },

  // ───────────── розтяжка (stretch) ─────────────
  {
    slug: 'side-bends',
    sortOrder: 42,
    category: ExerciseCategory.STRETCH,
    variantGroup: 'stretch',
    voicePattern: VoicePattern.TWIST,
    name: T('Нахили в сторони', 'Наклоны в стороны', 'Skłony w bok', 'Side bends'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Розтягує бічні м’язи корпусу й робить хребет гнучкішим.',
      'Растягивает боковые мышцы корпуса и делает позвоночник гибче.',
      'Rozciąga boczne mięśnie tułowia i uelastycznia kręgosłup.',
      'Stretches the sides of your torso and keeps the spine flexible.',
    ),
    description: T(
      'Ноги на ширині плечей, одна рука на поясі, друга вгору. Плавно нахиліться в бік, тягнучись рукою над головою. Поверніться й нахиліться в інший бік, змінивши руки.',
      'Ноги на ширине плеч, одна рука на поясе, другая вверх. Плавно наклонитесь в сторону, тянясь рукой над головой. Вернитесь и наклонитесь в другую сторону, сменив руки.',
      'Stopy na szerokość barków, jedna ręka na biodrze, druga w górze. Płynnie pochyl się w bok, sięgając ręką nad głową. Wróć i pochyl się w drugą stronę, zmieniając ręce.',
      'Feet shoulder-width, one hand on your hip and the other overhead. Smoothly bend to the side, reaching over your head. Come back up and bend the other way, switching arms.',
    ),
    aiCriteria:
      'Standing person alternately bending the torso to the left and right with one arm reaching overhead; the torso visibly tilts sideways between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRETCH, WorkoutType.MORNING],
    durationMin: 1,
    bodyImpact: { muscles: 30, heart: 15, brain: 15, bones: 25, energy: 35 },
    muscles: [
      T('Косі м’язи живота', 'Косые мышцы живота', 'Mięśnie skośne brzucha', 'Obliques'),
      T('Широкі м’язи спини', 'Широчайшие мышцы спины', 'Mięśnie najszersze grzbietu', 'Lats'),
    ],
    isActive: true,
  },
  {
    slug: 'forward-fold',
    sortOrder: 43,
    category: ExerciseCategory.STRETCH,
    variantGroup: 'stretch',
    voicePattern: VoicePattern.FOLD,
    name: T('Нахили вперед', 'Наклоны вперед', 'Skłony w przód', 'Forward folds'),
    targetReps: 10,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Розтягує задню поверхню ніг і спину, знімає напругу після сидіння.',
      'Растягивает заднюю поверхность ног и спину, снимает напряжение после сидения.',
      'Rozciąga tył nóg i plecy, rozluźnia po długim siedzeniu.',
      'Stretches the backs of the legs and the back, easing tension after sitting.',
    ),
    description: T(
      'Станьте рівно, ноги на ширині стегон. На видиху плавно нахиліться вперед, тягнучись руками до гомілок або підлоги, коліна можна трохи зігнути. На вдиху повільно випряміться.',
      'Встаньте ровно, ноги на ширине бедер. На выдохе плавно наклонитесь вперед, тянясь руками к голеням или полу, колени можно слегка согнуть. На вдохе медленно выпрямитесь.',
      'Stań prosto, stopy na szerokość bioder. Z wydechem płynnie pochyl się w przód, sięgając dłońmi do goleni lub podłogi, kolana możesz lekko ugiąć. Z wdechem powoli się wyprostuj.',
      'Stand tall, feet hip-width. Exhale and fold forward slowly, reaching toward your shins or the floor; soften your knees if needed. Inhale and roll back up slowly.',
    ),
    safetyInstructions: T(
      'Без ривків. Якщо паморочиться в голові — випрямляйтеся повільніше.',
      'Без рывков. Если кружится голова — выпрямляйтесь медленнее.',
      'Bez szarpnięć. Jeśli kręci się w głowie — prostuj się wolniej.',
      'No bouncing. If you feel dizzy, come up more slowly.',
    ),
    aiCriteria:
      'Standing person repeatedly bending forward from the hips with hands reaching toward the shins or floor, then standing back up; torso angle changes clearly between frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRETCH],
    durationMin: 1,
    bodyImpact: { muscles: 30, heart: 15, brain: 15, bones: 25, energy: 30 },
    muscles: [
      T('Задня поверхня стегна', 'Задняя поверхность бедра', 'Mięśnie dwugłowe uda', 'Hamstrings'),
      T('М’язи спини', 'Мышцы спины', 'Mięśnie pleców', 'Back muscles'),
      T('Литки', 'Икры', 'Łydki', 'Calves'),
    ],
    isActive: true,
  },
];
