import { AppLanguage, ExerciseCategory, VoicePattern, WorkoutType } from '../../common/enums';
import { LocalizedText } from '../../common/types';
import type { ExerciseSeed } from './exercises.seed-data';

/**
 * Каталог застосунку = РІВНО ті вправи, для яких є демо-ролики (mobile/assets/video). Назви, техніка й критерії
 * для AI написані за вмістом самих роликів (кадри переглянуто). Інші вправи з попередніх seed-файлів вимкнені
 * (`isActive: false`, див. exercises.seeder) — без відео їх не показуємо.
 *
 * Ролик → вправа: squat_v19 → squat · pushup_v10 → push-up · lunge30 → forward-lunge · mux → wall-sit ·
 * plank30 → plank · crunch30 → crunch · climber30 → mountain-climber · jacks_v12 → jumping-jacks ·
 * knees_v4 → high-knees · burpee30 → burpee.
 *
 * ⚠️ Загальні рекомендації, не медичні поради; польські тексти перевірити носієм.
 */

const L = AppLanguage;
const T = (uk: string, ru: string, pl: string, en: string): LocalizedText => ({
  [L.UK]: uk,
  [L.RU]: ru,
  [L.PL]: pl,
  [L.EN]: en,
});

const WHO = 'WHO guidelines on physical activity and sedentary behaviour, 2020';
const ACSM = "ACSM's Guidelines for Exercise Testing and Prescription, 11th ed.";

const LEGS = T('Ноги', 'Ноги', 'Nogi', 'Legs');
const GLUTES = T('Сідниці', 'Ягодицы', 'Pośladki', 'Glutes');
const CORE = T('Прес', 'Пресс', 'Mięśnie brzucha', 'Abs');
const CHEST = T('Груди', 'Грудь', 'Klatka piersiowa', 'Chest');
const ARMS = T('Руки', 'Руки', 'Ramiona', 'Arms');
const SHOULDERS = T('Плечі', 'Плечи', 'Barki', 'Shoulders');
const HEART = T('Серце', 'Сердце', 'Serce', 'Heart');

export const VIDEO_EXERCISE_SLUGS = [
  'squat',
  'push-up',
  'forward-lunge',
  'wall-sit',
  'plank',
  'crunch',
  'mountain-climber',
  'jumping-jacks',
  'high-knees',
  'burpee',
] as const;

export const VIDEO_EXERCISES_SEED: ExerciseSeed[] = [
  {
    slug: 'squat',
    sortOrder: 1,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.SQUAT,
    name: T('Присідання', 'Приседания', 'Przysiady', 'Squats'),
    targetReps: 10,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює ноги й сідниці — легше вставати зі стільця й підніматися сходами.',
      'Укрепляет ноги и ягодицы — легче вставать со стула и подниматься по лестнице.',
      'Wzmacnia nogi i pośladki — łatwiej wstać z krzesła i wchodzić po schodach.',
      'Strengthens legs and glutes, making it easier to stand up and climb stairs.',
    ),
    description: T(
      'Станьте прямо, стопи на ширині плечей, руки витягніть уперед. На вдиху опустіться, ніби сідаєте на стілець: коліна над стопами, спина рівна. На видиху підніміться.',
      'Встаньте прямо, стопы на ширине плеч, руки вытяните вперед. На вдохе опуститесь, будто садитесь на стул: колени над стопами, спина ровная. На выдохе поднимитесь.',
      'Stań prosto, stopy na szerokość barków, ręce wyciągnij przed siebie. Na wdechu zejdź w dół, jakbyś siadał na krześle: kolana nad stopami, plecy proste. Na wydechu wstań.',
      'Stand tall, feet shoulder-width apart, arms straight out in front. Breathing in, lower yourself as if sitting on a chair: knees over feet, back straight. Breathing out, stand up.',
    ),
    safetyInstructions: T(
      'Опускайтеся лише на комфортну глибину; за потреби поставте позаду стілець.',
      'Опускайтесь только на комфортную глубину; при необходимости поставьте сзади стул.',
      'Schodź tylko na wygodną głębokość; w razie potrzeby postaw z tyłu krzesło.',
      'Only go as low as is comfortable; put a chair behind you if needed.',
    ),
    aiCriteria:
      'Bodyweight squat, standing, arms forward: the hips go down with knees bending and come back up to standing, repeatedly. Partial depth is fine. A chair behind is fine.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 35, brain: 20, bones: 65, energy: 45 },
    muscles: [LEGS, GLUTES],
    isActive: true,
  },
  {
    slug: 'push-up',
    sortOrder: 2,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.PUSH,
    name: T('Віджимання', 'Отжимания', 'Pompki', 'Push-ups'),
    targetReps: 8,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює груди, руки й плечі — легше відчиняти двері, підводитися з підлоги.',
      'Укрепляет грудь, руки и плечи — легче открывать двери, подниматься с пола.',
      'Wzmacnia klatkę, ramiona i barki — łatwiej otwierać drzwi i wstawać z podłogi.',
      'Strengthens chest, arms and shoulders for everyday pushing and getting up off the floor.',
    ),
    description: T(
      'Упор лежачи: долоні трохи ширше плечей, тіло — рівна лінія від голови до п’ят. На вдиху зігніть руки й опустіть груди до підлоги. На видиху випряміть руки.',
      'Упор лежа: ладони чуть шире плеч, тело — ровная линия от головы до пят. На вдохе согните руки и опустите грудь к полу. На выдохе выпрямите руки.',
      'Podpór przodem: dłonie nieco szerzej niż barki, ciało w linii od głowy do pięt. Na wdechu ugnij ręce i opuść klatkę do podłogi. Na wydechu wyprostuj ręce.',
      'Plank position: hands slightly wider than shoulders, body in a straight line from head to heels. Breathing in, bend the arms and lower the chest. Breathing out, push back up.',
    ),
    safetyInstructions: T(
      'Важко — віджимайтеся з колін або від столу: це теж зараховується.',
      'Тяжело — отжимайтесь с колен или от стола: это тоже засчитывается.',
      'Za trudno — rób pompki z kolan lub przy stole: to też się liczy.',
      'Too hard? Do them from your knees or against a table — that counts too.',
    ),
    aiCriteria:
      'Push-up: hands on the floor (or knees down, or hands on a table/sofa — all acceptable), the body lowers by bending the elbows and rises again, repeatedly. A smaller range is fine.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 80, heart: 30, brain: 15, bones: 55, energy: 40 },
    muscles: [CHEST, ARMS, SHOULDERS],
    isActive: true,
  },
  {
    slug: 'forward-lunge',
    sortOrder: 3,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.LUNGE,
    name: T('Випади вперед', 'Выпады вперед', 'Wykroki w przód', 'Forward lunges'),
    targetReps: 10,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Тренує силу ніг і рівновагу — впевнений крок і менше ризик падіння.',
      'Тренирует силу ног и равновесие — уверенный шаг и меньше риск падения.',
      'Ćwiczy siłę nóg i równowagę — pewny krok i mniejsze ryzyko upadku.',
      'Builds leg strength and balance for a steadier step and fewer falls.',
    ),
    description: T(
      'Станьте прямо. На вдиху зробіть широкий крок уперед і опустіться: обидва коліна зігнуті, заднє — майже до підлоги. На видиху поверніться. Чергуйте ноги.',
      'Встаньте прямо. На вдохе сделайте широкий шаг вперед и опуститесь: оба колена согнуты, заднее — почти до пола. На выдохе вернитесь. Чередуйте ноги.',
      'Stań prosto. Na wdechu zrób szeroki krok w przód i opuść się: oba kolana ugięte, tylne prawie do podłogi. Na wydechu wróć. Zmieniaj nogi.',
      'Stand tall. Breathing in, take a big step forward and lower down: both knees bent, the back knee close to the floor. Breathing out, step back. Alternate legs.',
    ),
    safetyInstructions: T(
      'Для рівноваги можна триматися за спинку стільця; опускайтеся неглибоко.',
      'Для равновесия можно держаться за спинку стула; опускайтесь неглубоко.',
      'Dla równowagi możesz trzymać się oparcia krzesła; schodź płytko.',
      'Hold a chair back for balance if needed and keep the lunge shallow.',
    ),
    aiCriteria:
      'Forward lunge: from standing, the person steps one leg forward and lowers the body by bending both knees, then returns to standing, alternating legs. Shallow lunges and holding a chair are fine.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH, WorkoutType.COORDINATION],
    durationMin: 2,
    bodyImpact: { muscles: 75, heart: 35, brain: 35, bones: 65, energy: 45 },
    muscles: [LEGS, GLUTES],
    isActive: true,
  },
  {
    slug: 'wall-sit',
    sortOrder: 4,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.HOLD,
    name: T('«Стільчик» біля стіни', '«Стульчик» у стены', '„Krzesełko” przy ścianie', 'Wall sit'),
    targetReps: null,
    targetSeconds: 20,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює стегна без навантаження на суглоби рухом — опора для колін.',
      'Укрепляет бедра без нагрузки на суставы движением — опора для коленей.',
      'Wzmacnia uda bez obciążania stawów ruchem — wsparcie dla kolan.',
      'Strengthens the thighs without joint-loading movement — good support for the knees.',
    ),
    description: T(
      'Притисніться спиною до стіни й з’їдьте вниз, ніби сідаєте на невидимий стілець: коліна над стопами, руки витягнуті вперед. Тримайте положення й дихайте рівно.',
      'Прижмитесь спиной к стене и съедьте вниз, будто садитесь на невидимый стул: колени над стопами, руки вытянуты вперед. Держите положение и дышите ровно.',
      'Oprzyj plecy o ścianę i zjedź w dół, jakbyś siadał na niewidzialnym krześle: kolana nad stopami, ręce wyciągnięte przed siebie. Utrzymaj pozycję i oddychaj równo.',
      'Press your back against a wall and slide down as if sitting on an invisible chair: knees over feet, arms straight out. Hold the position and breathe evenly.',
    ),
    safetyInstructions: T(
      'Не опускайтеся нижче, ніж комфортно для колін. Біль — одразу встаньте.',
      'Не опускайтесь ниже, чем комфортно для коленей. Боль — сразу встаньте.',
      'Nie schodź niżej, niż jest wygodnie dla kolan. Ból — od razu wstań.',
      'Do not go lower than is comfortable for your knees. Stop at once if it hurts.',
    ),
    aiCriteria:
      'HOLD exercise: the person sits against a wall with knees bent (thighs roughly towards horizontal, higher is fine), back on the wall, and holds this position for most frames.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 1,
    bodyImpact: { muscles: 70, heart: 25, brain: 15, bones: 50, energy: 30 },
    muscles: [LEGS, GLUTES],
    isActive: true,
  },
  {
    slug: 'plank',
    sortOrder: 5,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.HOLD,
    name: T(
      'Планка на передпліччях',
      'Планка на предплечьях',
      'Deska na przedramionach',
      'Forearm plank',
    ),
    targetReps: null,
    targetSeconds: 20,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює м’язи кору — тримає спину рівно й розвантажує поперек.',
      'Укрепляет мышцы кора — держит спину ровно и разгружает поясницу.',
      'Wzmacnia mięśnie głębokie — trzyma plecy prosto i odciąża lędźwia.',
      'Strengthens the core to keep the back straight and ease the lower back.',
    ),
    description: T(
      'Упор на передпліччя й носки: лікті під плечима, тіло — рівна лінія від голови до п’ят, живіт підтягнутий. Тримайте положення й дихайте рівно.',
      'Упор на предплечья и носки: локти под плечами, тело — ровная линия от головы до пят, живот подтянут. Держите положение и дышите ровно.',
      'Podpór na przedramionach i palcach stóp: łokcie pod barkami, ciało w linii od głowy do pięt, brzuch napięty. Utrzymaj pozycję i oddychaj równo.',
      'Rest on forearms and toes: elbows under shoulders, body straight from head to heels, belly tight. Hold the position and breathe evenly.',
    ),
    safetyInstructions: T(
      'Важко — тримайте планку з колін. Не затримуйте дихання.',
      'Тяжело — держите планку с колен. Не задерживайте дыхание.',
      'Za trudno — rób deskę z kolan. Nie wstrzymuj oddechu.',
      'Too hard? Hold the plank on your knees. Do not hold your breath.',
    ),
    aiCriteria:
      'HOLD exercise: forearm plank (on toes or on knees), body roughly straight, held for most frames. Hips slightly high or low is a minor issue.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 1,
    bodyImpact: { muscles: 70, heart: 25, brain: 20, bones: 40, energy: 35 },
    muscles: [CORE, SHOULDERS],
    isActive: true,
  },
  {
    slug: 'crunch',
    sortOrder: 6,
    category: ExerciseCategory.STRENGTH,
    variantGroup: null,
    voicePattern: VoicePattern.RAISE,
    name: T('Скручування на прес', 'Скручивания на пресс', 'Brzuszki', 'Crunches'),
    targetReps: 12,
    targetSeconds: null,
    recordMaxSec: 40,
    demoVideoUrl: null,
    benefit: T(
      'Зміцнює м’язи живота — підтримка спини й постави.',
      'Укрепляет мышцы живота — поддержка спины и осанки.',
      'Wzmacnia mięśnie brzucha — wsparcie dla pleców i postawy.',
      'Strengthens the abs to support the back and posture.',
    ),
    description: T(
      'Ляжте на спину, ноги зігнуті, стопи на підлозі, долоні за головою. На видиху підніміть голову й плечі, скручуючи корпус до колін. На вдиху повільно опустіться.',
      'Лягте на спину, ноги согнуты, стопы на полу, ладони за головой. На выдохе поднимите голову и плечи, скручивая корпус к коленям. На вдохе медленно опуститесь.',
      'Połóż się na plecach, nogi ugięte, stopy na podłodze, dłonie za głową. Na wydechu unieś głowę i barki, skręcając tułów do kolan. Na wdechu powoli opuść się.',
      'Lie on your back, knees bent, feet on the floor, hands behind your head. Breathing out, lift head and shoulders curling towards the knees. Breathing in, lower slowly.',
    ),
    safetyInstructions: T(
      'Не тягніть голову руками — піднімайтеся за рахунок живота.',
      'Не тяните голову руками — поднимайтесь за счет живота.',
      'Nie ciągnij głowy rękami — unoś się dzięki mięśniom brzucha.',
      'Do not pull on your head — lift with your abs.',
    ),
    aiCriteria:
      'Crunch: lying on the back with knees bent, the person repeatedly lifts head and shoulders off the floor towards the knees and lowers them again. A small lift is fine.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 65, heart: 20, brain: 15, bones: 25, energy: 35 },
    muscles: [CORE],
    isActive: true,
  },
  {
    slug: 'mountain-climber',
    sortOrder: 7,
    category: ExerciseCategory.CARDIO,
    variantGroup: null,
    voicePattern: VoicePattern.MARCH,
    name: T('«Скелелаз»', '«Скалолаз»', '„Wspinacz”', 'Mountain climbers'),
    targetReps: null,
    targetSeconds: 20,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Розганяє пульс і зміцнює прес та плечі одночасно.',
      'Разгоняет пульс и укрепляет пресс и плечи одновременно.',
      'Podnosi tętno i jednocześnie wzmacnia brzuch i barki.',
      'Raises the heart rate while strengthening the core and shoulders.',
    ),
    description: T(
      'Упор лежачи на прямих руках. По черзі підтягуйте коліна до грудей у зручному темпі, тримаючи спину рівною. Дихайте рівно.',
      'Упор лежа на прямых руках. Поочередно подтягивайте колени к груди в удобном темпе, держа спину ровной. Дышите ровно.',
      'Podpór przodem na prostych rękach. Na zmianę przyciągaj kolana do klatki w wygodnym tempie, trzymając plecy prosto. Oddychaj równo.',
      'High plank on straight arms. Alternately draw the knees towards the chest at a comfortable pace, back straight. Breathe evenly.',
    ),
    safetyInstructions: T(
      'Повільний темп — нормально. Можна спиратися руками на диван чи стіл.',
      'Медленный темп — нормально. Можно опираться руками на диван или стол.',
      'Wolne tempo jest w porządku. Możesz opierać ręce o kanapę lub stół.',
      'A slow pace is fine. You can rest your hands on a sofa or table.',
    ),
    aiCriteria:
      'Mountain climbers: in a plank on straight arms (hands on the floor or on furniture), the person alternately brings one knee towards the chest and back. Slow pace is fine.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO, WorkoutType.STRENGTH],
    durationMin: 1,
    bodyImpact: { muscles: 60, heart: 70, brain: 25, bones: 35, energy: 60 },
    muscles: [CORE, SHOULDERS, LEGS],
    isActive: true,
  },
  {
    slug: 'jumping-jacks',
    sortOrder: 8,
    category: ExerciseCategory.CARDIO,
    variantGroup: null,
    voicePattern: VoicePattern.JACKS,
    name: T('Стрибки «зірочка»', 'Прыжки «звездочка»', 'Pajacyki', 'Jumping jacks'),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Швидко розігріває тіло й розганяє кровообіг — тренування для серця.',
      'Быстро разогревает тело и разгоняет кровообращение — тренировка для сердца.',
      'Szybko rozgrzewa ciało i pobudza krążenie — trening dla serca.',
      'Warms you up quickly and boosts circulation — a workout for the heart.',
    ),
    description: T(
      'Станьте прямо. Стрибком розставте ноги й підніміть руки через сторони вгору, наступним стрибком поверніться. Без стрибків — по черзі відставляйте ногу вбік.',
      'Встаньте прямо. Прыжком расставьте ноги и поднимите руки через стороны вверх, следующим прыжком вернитесь. Без прыжков — поочередно отставляйте ногу в сторону.',
      'Stań prosto. Podskokiem rozstaw nogi i unieś ręce bokami w górę, kolejnym podskokiem wróć. Bez skakania — na zmianę odstawiaj nogę w bok.',
      'Stand tall. Jump the feet apart while raising the arms overhead, then jump back. No-jump version: step one foot out to the side at a time.',
    ),
    safetyInstructions: T(
      'Варіант без стрибків теж зараховується — бережіть коліна.',
      'Вариант без прыжков тоже засчитывается — берегите колени.',
      'Wersja bez skakania też się liczy — oszczędzaj kolana.',
      'The no-jump version counts too — go easy on your knees.',
    ),
    aiCriteria:
      'Jumping jacks (or the low-impact step-out version): legs go apart and together while the arms rise to the sides/overhead and come down, repeatedly.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO, WorkoutType.WARMUP],
    durationMin: 1,
    bodyImpact: { muscles: 40, heart: 80, brain: 30, bones: 50, energy: 70 },
    muscles: [LEGS, SHOULDERS, HEART],
    isActive: true,
  },
  {
    slug: 'high-knees',
    sortOrder: 9,
    category: ExerciseCategory.CARDIO,
    variantGroup: null,
    voicePattern: VoicePattern.MARCH,
    name: T(
      'Біг на місці з високими колінами',
      'Бег на месте с высокими коленями',
      'Bieg w miejscu z wysokimi kolanami',
      'High knees',
    ),
    targetReps: null,
    targetSeconds: 30,
    recordMaxSec: 30,
    demoVideoUrl: null,
    benefit: T(
      'Тренує серце й витривалість, зміцнює ноги.',
      'Тренирует сердце и выносливость, укрепляет ноги.',
      'Ćwiczy serce i wytrzymałość, wzmacnia nogi.',
      'Trains the heart and stamina and strengthens the legs.',
    ),
    description: T(
      'Біжіть на місці, по черзі високо піднімаючи коліна, руки працюють у такт. Повільніший варіант — крокування на місці з високими колінами.',
      'Бегите на месте, поочередно высоко поднимая колени, руки работают в такт. Более медленный вариант — шаг на месте с высокими коленями.',
      'Biegnij w miejscu, na zmianę wysoko unosząc kolana, ręce pracują do rytmu. Wolniejsza wersja — marsz w miejscu z wysokimi kolanami.',
      'Run on the spot, lifting the knees high one after another, arms swinging along. Slower version: march on the spot with high knees.',
    ),
    safetyInstructions: T(
      'Крокування замість бігу — теж зараховується.',
      'Шаг вместо бега — тоже засчитывается.',
      'Marsz zamiast biegu też się liczy.',
      'Marching instead of running counts too.',
    ),
    aiCriteria:
      'High knees: running or marching on the spot, alternately lifting the knees (higher is better, but moderate height is fine), arms moving.',
    sourceTitle: WHO,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO],
    durationMin: 1,
    bodyImpact: { muscles: 45, heart: 80, brain: 25, bones: 50, energy: 70 },
    muscles: [LEGS, HEART],
    isActive: true,
  },
  {
    slug: 'burpee',
    sortOrder: 10,
    category: ExerciseCategory.CARDIO,
    variantGroup: null,
    voicePattern: VoicePattern.SQUAT,
    name: T('Берпі', 'Берпи', 'Burpees', 'Burpees'),
    targetReps: 6,
    targetSeconds: null,
    recordMaxSec: 45,
    demoVideoUrl: null,
    benefit: T(
      'Задіює все тіло й серце за кілька повторів — максимум користі за хвилину.',
      'Задействует все тело и сердце за несколько повторов — максимум пользы за минуту.',
      'Angażuje całe ciało i serce w kilku powtórzeniach — maksimum korzyści w minutę.',
      'Works the whole body and heart in a few reps — maximum benefit in a minute.',
    ),
    description: T(
      'Присядьте й поставте долоні на підлогу, відставте ноги назад в упор лежачи, поверніть ноги до рук і випряміться, піднявши руки вгору. Повторіть у спокійному темпі.',
      'Присядьте и поставьте ладони на пол, отставьте ноги назад в упор лежа, верните ноги к рукам и выпрямитесь, подняв руки вверх. Повторите в спокойном темпе.',
      'Przykucnij i połóż dłonie na podłodze, odstaw nogi w tył do podporu, wróć nogami do rąk i wyprostuj się, unosząc ręce w górę. Powtarzaj w spokojnym tempie.',
      'Squat down and put your hands on the floor, step or jump the feet back into a plank, bring the feet back to the hands and stand up with arms overhead. Repeat calmly.',
    ),
    safetyInstructions: T(
      'Ноги можна відставляти кроками, без стрибків. Паморочиться голова — зупиніться.',
      'Ноги можно отставлять шагами, без прыжков. Кружится голова — остановитесь.',
      'Nogi możesz odstawiać krokami, bez skakania. Kręci się w głowie — przerwij.',
      'Step the feet back instead of jumping if you like. Stop if you feel dizzy.',
    ),
    aiCriteria:
      'Burpee (jump or step version): squat with hands to the floor, feet go back into a plank, feet return and the person stands up, often with arms overhead; repeated. Slow, stepped execution is fine.',
    sourceTitle: ACSM,
    sourceUrl: null,
    workoutTypes: [WorkoutType.CARDIO, WorkoutType.STRENGTH],
    durationMin: 2,
    bodyImpact: { muscles: 75, heart: 80, brain: 30, bones: 55, energy: 75 },
    muscles: [LEGS, CHEST, CORE, HEART],
    isActive: true,
  },
];
