import {
  Activity,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Bone,
  Brain,
  Bell,
  BellRing,
  CalendarCheck,
  CalendarDays,
  Camera,
  CameraOff,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  ClipboardList,
  Clock,
  Coins,
  Copy,
  Dumbbell,
  Film,
  Flame,
  Footprints,
  Globe,
  HandHeart,
  Heart,
  HeartPulse,
  House,
  Image,
  ImageOff,
  Info,
  Key,
  Languages,
  Leaf,
  Lock,
  LogOut,
  Mail,
  Minus,
  Mountain,
  Move,
  PartyPopper,
  Pencil,
  PersonStanding,
  PiggyBank,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  RotateCw,
  Send,
  Settings,
  Share2,
  SkipForward,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  Sprout,
  StretchHorizontal,
  Sun,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  TriangleAlert,
  UserRound,
  Volume2,
  VolumeX,
  Users,
  Wallet,
  WifiOff,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import { colors, type ColorToken } from '@/theme';

/**
 * Єдиний набір іконок застосунку (Lucide: однакова товщина лінії, заокруглені кінці).
 * Екрани звертаються за СМИСЛОВОЮ назвою (`home`, `progress`…), а не за назвою бібліотеки:
 * набір можна замінити в одному місці.
 */
export const ICONS = {
  home: House,
  progress: Activity,
  plan: CalendarDays,
  profile: UserRound,
  check: Check,
  'check-circle': CircleCheck,
  x: X,
  plus: Plus,
  minus: Minus,
  lock: Lock,
  flame: Flame,
  camera: Camera,
  'camera-off': CameraOff,
  image: Image,
  'image-off': ImageOff,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bell: Bell,
  'bell-ring': BellRing,
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  receipt: Receipt,
  leaf: Leaf,
  sprout: Sprout,
  party: PartyPopper,
  mail: Mail,
  phone: Smartphone,
  heart: Heart,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  wind: Wind,
  footprints: Footprints,
  'person-standing': PersonStanding,
  trophy: Trophy,
  shield: ShieldCheck,
  info: Info,
  send: Send,
  copy: Copy,
  share: Share2,
  logout: LogOut,
  trash: Trash2,
  language: Languages,
  play: Play,
  film: Film,
  alert: TriangleAlert,
  'alert-circle': CircleAlert,
  'wifi-off': WifiOff,
  clock: Clock,
  timer: Timer,
  sparkles: Sparkles,
  users: Users,
  clipboard: ClipboardList,
  help: CircleQuestionMark,
  edit: Pencil,
  refresh: RefreshCw,
  settings: Settings,
  target: Target,
  key: Key,
  sun: Sun,
  'hand-heart': HandHeart,
  globe: Globe,
  'calendar-check': CalendarCheck,
  'trending-up': TrendingUp,
  rotate: RotateCw,
  stretch: Move,
  brain: Brain,
  bone: Bone,
  zap: Zap,
  volume: Volume2,
  'volume-off': VolumeX,
  piggy: PiggyBank,
  skip: SkipForward,
  square: Square,
  'square-check': SquareCheck,
  'arrow-down-up': ArrowDownUp,
  'stretch-horizontal': StretchHorizontal,
  mountain: Mountain,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  size?: number;
  /** Токен кольору теми або довільний рядок (наприклад, з анімації) */
  color?: ColorToken | (string & {});
  strokeWidth?: number;
}

export function Icon({ name, size = 22, color = 'ink', strokeWidth = 2 }: IconProps) {
  const Cmp = ICONS[name];
  const resolved = color in colors ? colors[color as ColorToken] : color;
  return <Cmp size={size} color={resolved} strokeWidth={strokeWidth} absoluteStrokeWidth accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />;
}
